/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/customer_management/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
export default function Page() {
  return (
    <div className={`theme-admin bg-background text-on-background font-body-md text-body-md antialiased overflow-hidden flex h-screen w-full`}>
{/*  SideNavBar  */}
<aside className="bg-surface-container-lowest border-r border-outline-variant h-screen w-64 fixed left-0 top-0 z-50 flex flex-col py-md space-y-xs transition-all duration-150 ease-in-out">
<div className="px-lg py-md mb-sm">
<h2 className="font-h3 text-h3 text-on-surface tracking-tight">AdminConsole</h2>
<p className="font-label-sm text-label-sm text-on-surface-variant mt-xs">Enterprise Suite</p>
</div>
<nav className="flex-1 flex flex-col gap-xs px-sm">
{/*  Inactive  */}
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low transition-colors duration-150" href="#">
<span className="material-symbols-outlined">dashboard</span>
<span className="font-label-md text-label-md">Overview</span>
</a>
{/*  Inactive  */}
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low transition-colors duration-150" href="#">
<span className="material-symbols-outlined">inventory_2</span>
<span className="font-label-md text-label-md">Inventory</span>
</a>
{/*  Inactive  */}
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low transition-colors duration-150" href="#">
<span className="material-symbols-outlined">shopping_cart</span>
<span className="font-label-md text-label-md">Orders</span>
</a>
{/*  Active  */}
<a className="flex items-center gap-md px-md py-sm rounded-lg bg-surface-container text-primary border-r-4 border-primary" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1" }}>group</span>
<span className="font-label-md text-label-md font-bold">Customers</span>
</a>
{/*  Inactive  */}
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low transition-colors duration-150 mt-auto" href="#">
<span className="material-symbols-outlined">settings</span>
<span className="font-label-md text-label-md">Settings</span>
</a>
</nav>
</aside>
{/*  Main Content Wrapper  */}
<div className="flex-1 ml-64 flex flex-col min-w-0 h-screen">
{/*  TopAppBar  */}
<header className="bg-surface-container-lowest border-b border-outline-variant flex items-center justify-between px-lg h-16 w-full shrink-0 z-40 transition-colors duration-200">
<div className="flex items-center gap-md">
<div className="relative flex items-center">
<span className="material-symbols-outlined absolute left-sm text-on-surface-variant text-[20px]">search</span>
<input className="pl-xl pr-md py-sm bg-surface-container-low border border-outline-variant rounded-lg font-body-sm text-body-sm text-on-surface focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary w-64 transition-all" placeholder="Search AdminPanel..." type="text" />
</div>
</div>
<div className="flex items-center gap-sm">
<button className="p-sm rounded-full text-on-surface-variant hover:bg-surface-container-low hover:text-on-surface transition-colors">
<span className="material-symbols-outlined">notifications</span>
</button>
<button className="p-sm rounded-full text-on-surface-variant hover:bg-surface-container-low hover:text-on-surface transition-colors">
<span className="material-symbols-outlined">help</span>
</button>
<button className="ml-sm flex items-center gap-sm p-xs pr-md rounded-full border border-outline-variant hover:bg-surface-container-low transition-colors">
<div className="w-8 h-8 rounded-full bg-surface-variant flex items-center justify-center text-primary font-label-md">
<span className="material-symbols-outlined">account_circle</span>
</div>
<span className="font-label-md text-label-md text-on-surface">Admin User</span>
</button>
</div>
</header>
{/*  Main Canvas  */}
<main className="flex-1 overflow-y-auto p-lg bg-background">
<div className="mb-lg flex items-center justify-between">
<div>
<h1 className="font-h1 text-h1 text-on-surface">Customer Database</h1>
<p className="font-body-md text-body-md text-on-surface-variant mt-xs">Manage your enterprise clientele and view transaction histories.</p>
</div>
<button className="bg-primary text-on-primary px-md py-sm rounded-lg font-label-md text-label-md flex items-center gap-sm hover:bg-surface-tint transition-colors">
<span className="material-symbols-outlined text-[18px]">add</span>
                    New Customer
                </button>
</div>
{/*  Dashboard Split Layout  */}
<div className="grid grid-cols-1 xl:grid-cols-3 gap-lg h-[calc(100vh-12rem)] min-h-[600px]">
{/*  Left: Directory Table (Span 2)  */}
<div className="xl:col-span-2 bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden flex flex-col shadow-sm">
<div className="px-md py-sm border-b border-outline-variant bg-surface flex items-center justify-between">
<div className="flex items-center gap-sm">
<span className="material-symbols-outlined text-on-surface-variant">filter_list</span>
<span className="font-label-md text-label-md text-on-surface">All Customers</span>
</div>
<button className="text-on-surface-variant hover:text-on-surface p-xs rounded hover:bg-surface-variant transition-colors">
<span className="material-symbols-outlined">more_horiz</span>
</button>
</div>
<div className="flex-1 overflow-auto">
<table className="w-full text-left border-collapse">
<thead className="bg-surface-container-low sticky top-0 border-b border-outline-variant z-10">
<tr>
<th className="py-sm px-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider">Name</th>
<th className="py-sm px-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider">Email</th>
<th className="py-sm px-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider">Total Orders</th>
<th className="py-sm px-md font-label-sm text-label-sm text-on-surface-variant uppercase tracking-wider">Status</th>
</tr>
</thead>
<tbody className="divide-y divide-outline-variant">
{/*  Active Row Example  */}
<tr className="hover:bg-surface-container-low cursor-pointer transition-colors bg-surface-container-lowest border-l-4 border-l-transparent">
<td className="py-sm px-md">
<div className="flex items-center gap-md">
<div className="w-10 h-10 rounded-full overflow-hidden bg-surface-variant flex-shrink-0">
<img alt="Sarah Jenkins portrait" className="w-full h-full object-cover" data-alt="close up professional headshot of a smiling young woman with dark hair against a light grey background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBxTqgggN41JWRX7tyH3hvYRKkN-vXt8-6N8WVI6CxCsX32YHurzlfZ25LbLaGoHxGMLTDy58qHsrW1dtcZJ4yXDj3QL8Dbb8mVngg6OYiVzKxxE2igq5C1V0YSdzPtPpOYHJRCz-AlL5XWaUURMmks7sKpvj7V7V-apisvhrpicwqToHxAezpAeg4Pvr-BNppodnbevTrWs48HroBb2etzFyCy7ty882M1uEn68OBbVMzUgqBgTAYFLi-Hn77tbVPw3ihfrqsfQwxU" />
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Sarah Jenkins</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Acme Corp</div>
</div>
</div>
</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">s.jenkins@acmecorp.com</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">142</td>
<td className="py-sm px-md">
<span className="inline-flex items-center px-sm py-xs rounded-full bg-primary-container text-on-primary-container font-label-sm text-label-sm">
                                            Active
                                        </span>
</td>
</tr>
{/*  Regular Rows  */}
<tr className="hover:bg-surface-container-low cursor-pointer transition-colors bg-surface border-l-4 border-l-primary shadow-[inset_0_1px_0_0_#bccbb4,inset_0_-1px_0_0_#bccbb4] relative z-0">
<td className="py-sm px-md">
<div className="flex items-center gap-md">
<div className="w-10 h-10 rounded-full overflow-hidden bg-surface-variant flex-shrink-0">
<img alt="Marcus Chen portrait" className="w-full h-full object-cover" data-alt="professional headshot of a smiling asian man wearing a suit jacket against a blurred office background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuA0_Dj3zmK0lQbbz4XwbrScAZhatxopWp7fjFXGNI9tcZZpe0yPT_ZtiVPN5uXRNCar7Nnh4zOzVfabvSYVi6yUoiy38f4R3cu6dKuw5k7cz2NSBEdiB_SC2gR9BLNA_DjioOSf9sy_I3UzYyLvNJHLozcF4Htmse5b7_dCZyx8YMBlvBCl-TeqkmQvu6d74FHKfqFFVQ3cTUpBoNTFGb-RehhBaZlyXPwQqHB3mTt095udMycU3lvFH_nJhsBvHbkQkEBaByG_FToT" />
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Marcus Chen</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">TechFlow Inc</div>
</div>
</div>
</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">m.chen@techflow.io</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">87</td>
<td className="py-sm px-md">
<span className="inline-flex items-center px-sm py-xs rounded-full bg-primary-container text-on-primary-container font-label-sm text-label-sm">
                                            Active
                                        </span>
</td>
</tr>
<tr className="hover:bg-surface-container-low cursor-pointer transition-colors bg-surface-container-lowest border-l-4 border-l-transparent">
<td className="py-sm px-md">
<div className="flex items-center gap-md">
<div className="w-10 h-10 rounded-full bg-secondary-container text-on-secondary-container flex items-center justify-center font-h3 flex-shrink-0">
                                                EW
                                            </div>
<div>
<div className="font-label-md text-label-md text-on-surface">Elena Weaver</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Global Logistics</div>
</div>
</div>
</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">elena.w@globallogistics.net</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">34</td>
<td className="py-sm px-md">
<span className="inline-flex items-center px-sm py-xs rounded-full bg-surface-variant text-on-surface-variant font-label-sm text-label-sm">
                                            Inactive
                                        </span>
</td>
</tr>
<tr className="hover:bg-surface-container-low cursor-pointer transition-colors bg-surface-container-lowest border-l-4 border-l-transparent">
<td className="py-sm px-md">
<div className="flex items-center gap-md">
<div className="w-10 h-10 rounded-full overflow-hidden bg-surface-variant flex-shrink-0">
<img alt="David Miller portrait" className="w-full h-full object-cover" data-alt="professional headshot of a middle aged man with short hair and stubble wearing a light blue shirt" src="https://lh3.googleusercontent.com/aida-public/AB6AXuB_OAAnRCue2XDsQKqnboStHY5ufhBC0VeAJJardCWvP2FizLEtUbAHAPBIcTN0gdTX4YpIZ_sNwB5QVyNGMgbE8N1CaWUgSzmXODq15p29XLEk3kSKiizQsB66q6cUAnMz0tfY-knz1ajLM6E8dednQnw7J8zS12vCc2Q1zOWvgYFXaLmToLACvaAmJoMtUPxX2Ap3l5nMBdcYaanEBnx7ktplojUPQcpBAoiMWKUrlchl4OG2Sg9UE4YAgIF_3LGSeA7srAYZWm0D" />
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">David Miller</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Miller &amp; Co</div>
</div>
</div>
</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">dmiller@millerco.com</td>
<td className="py-sm px-md font-body-sm text-body-sm text-on-surface">12</td>
<td className="py-sm px-md">
<span className="inline-flex items-center px-sm py-xs rounded-full bg-error-container text-on-error-container font-label-sm text-label-sm">
                                            Suspended
                                        </span>
</td>
</tr>
</tbody>
</table>
</div>
{/*  Pagination  */}
<div className="px-md py-sm border-t border-outline-variant bg-surface flex items-center justify-between">
<span className="font-body-sm text-body-sm text-on-surface-variant">Showing 1 to 4 of 240 entries</span>
<div className="flex items-center gap-sm">
<button className="p-xs rounded border border-outline-variant text-on-surface-variant disabled:opacity-50" disabled>
<span className="material-symbols-outlined text-[18px]">chevron_left</span>
</button>
<button className="p-xs rounded border border-outline-variant text-on-surface hover:bg-surface-container-low">
<span className="material-symbols-outlined text-[18px]">chevron_right</span>
</button>
</div>
</div>
</div>
{/*  Right: Details & Tx History (Span 1)  */}
<div className="xl:col-span-1 bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden flex flex-col shadow-sm">
{/*  Profile Header  */}
<div className="p-md border-b border-outline-variant flex items-start justify-between bg-surface-bright relative">
<div className="absolute inset-0 h-16 bg-gradient-to-r from-surface-container to-surface-container-highest opacity-50 z-0"></div>
<div className="flex flex-col items-center text-center w-full z-10 pt-sm">
<div className="w-20 h-20 rounded-full overflow-hidden border-4 border-surface-container-lowest shadow-sm mb-sm bg-surface-variant">
<img alt="Marcus Chen portrait" className="w-full h-full object-cover" data-alt="professional headshot of a smiling asian man wearing a suit jacket against a blurred office background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDTI8HSALml2J4REoIj8oHLQMheVbnxAdXSWogr0eB8uHxuqxDSK8wOHq6lwct8IE0Ht965_ERrxlQJllme5GfGo--E_mvK5r4ARDiw_eCx5bdor6UY9CXsyK0SOlP1eeE3aNTqSQYPATfA-Ui-SRycgUemEsSniee1-nQC6QgBBi2gX8WlnoO9Of-gRZLpFRltJRTr-6xx0Z6J3aWeRGTbBoZNu5Qcb7T6HCboDH9VxAIiDzlKs7ulgUO7HIZIH1UsA3QmnK2551GI" />
</div>
<h3 className="font-h3 text-h3 text-on-surface">Marcus Chen</h3>
<p className="font-body-sm text-body-sm text-on-surface-variant">m.chen@techflow.io</p>
<div className="mt-md flex gap-sm">
<button className="px-md py-xs border border-outline-variant rounded bg-surface-container-lowest font-label-sm text-label-sm text-on-surface hover:bg-surface-container-low transition-colors">Message</button>
<button className="px-md py-xs border border-outline-variant rounded bg-surface-container-lowest font-label-sm text-label-sm text-on-surface hover:bg-surface-container-low transition-colors flex items-center gap-xs">
<span className="material-symbols-outlined text-[16px]">edit</span> Edit
                                </button>
</div>
</div>
</div>
{/*  Stats Row  */}
<div className="grid grid-cols-2 divide-x divide-outline-variant border-b border-outline-variant bg-surface-container-lowest">
<div className="p-md text-center">
<div className="font-label-sm text-label-sm text-on-surface-variant uppercase mb-xs">LTV</div>
<div className="font-h2 text-h2 text-on-surface">$14,205</div>
</div>
<div className="p-md text-center">
<div className="font-label-sm text-label-sm text-on-surface-variant uppercase mb-xs">Avg Order</div>
<div className="font-h2 text-h2 text-on-surface">$163</div>
</div>
</div>
{/*  Tx History Header  */}
<div className="px-md py-sm bg-surface-container-low border-b border-outline-variant flex items-center justify-between">
<h4 className="font-label-md text-label-md text-on-surface flex items-center gap-sm">
<span className="material-symbols-outlined text-[18px]">receipt_long</span>
                            Tx History Per user
                        </h4>
<a className="font-label-sm text-label-sm text-secondary hover:underline" href="#">View All</a>
</div>
{/*  Tx List  */}
<div className="flex-1 overflow-y-auto">
<ul className="divide-y divide-outline-variant">
<li className="p-md hover:bg-surface-container-lowest transition-colors flex items-center justify-between">
<div className="flex items-start gap-md">
<div className="w-10 h-10 rounded bg-surface-variant flex items-center justify-center text-on-surface-variant">
<span className="material-symbols-outlined">inventory</span>
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Order #ORD-8821</div>
<div className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Enterprise Server Rack</div>
<div className="font-label-sm text-label-sm text-on-surface-variant mt-xs">Oct 24, 2023</div>
</div>
</div>
<div className="text-right">
<div className="font-label-md text-label-md text-on-surface">$2,450.00</div>
<div className="font-label-sm text-label-sm text-primary mt-xs">Completed</div>
</div>
</li>
<li className="p-md hover:bg-surface-container-lowest transition-colors flex items-center justify-between bg-surface">
<div className="flex items-start gap-md">
<div className="w-10 h-10 rounded bg-surface-variant flex items-center justify-center text-on-surface-variant">
<span className="material-symbols-outlined">description</span>
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Invoice #INV-4490</div>
<div className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Annual Maintenance Contract</div>
<div className="font-label-sm text-label-sm text-on-surface-variant mt-xs">Sep 12, 2023</div>
</div>
</div>
<div className="text-right">
<div className="font-label-md text-label-md text-on-surface">$1,200.00</div>
<div className="font-label-sm text-label-sm text-primary mt-xs">Completed</div>
</div>
</li>
<li className="p-md hover:bg-surface-container-lowest transition-colors flex items-center justify-between">
<div className="flex items-start gap-md">
<div className="w-10 h-10 rounded bg-surface-variant flex items-center justify-center text-on-surface-variant">
<span className="material-symbols-outlined">inventory</span>
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Order #ORD-8705</div>
<div className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Cisco Networking Gear</div>
<div className="font-label-sm text-label-sm text-on-surface-variant mt-xs">Aug 05, 2023</div>
</div>
</div>
<div className="text-right">
<div className="font-label-md text-label-md text-on-surface">$4,120.00</div>
<div className="font-label-sm text-label-sm text-primary mt-xs">Completed</div>
</div>
</li>
<li className="p-md hover:bg-surface-container-lowest transition-colors flex items-center justify-between bg-surface">
<div className="flex items-start gap-md">
<div className="w-10 h-10 rounded bg-surface-variant flex items-center justify-center text-on-surface-variant">
<span className="material-symbols-outlined text-error">assignment_return</span>
</div>
<div>
<div className="font-label-md text-label-md text-on-surface">Return #RET-092</div>
<div className="font-body-sm text-body-sm text-on-surface-variant mt-xs">Defective Switch Module</div>
<div className="font-label-sm text-label-sm text-on-surface-variant mt-xs">Jul 18, 2023</div>
</div>
</div>
<div className="text-right">
<div className="font-label-md text-label-md text-on-surface">-$450.00</div>
<div className="font-label-sm text-label-sm text-error mt-xs">Refunded</div>
</div>
</li>
</ul>
</div>
</div>
</div>
</main>
</div>
    </div>
  );
}
