/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/settings_security/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
export default function Page() {
  return (
    <div className={`theme-admin bg-surface-container text-on-surface flex min-h-screen`}>
{/*  SideNavBar (from JSON)  */}
<aside className="h-screen w-64 fixed left-0 top-0 z-50 border-r border-outline-variant bg-surface-container-lowest flex flex-col py-4 space-y-1">
<div className="px-6 py-4 mb-xl">
<h1 className="text-lg font-black tracking-tight text-on-surface">AdminConsole</h1>
<p className="font-body-sm text-body-sm text-on-surface-variant">Enterprise Suite</p>
</div>
<nav className="flex-1 flex flex-col space-y-1 px-sm">
{/*  Inactive  */}
<a className="flex items-center space-x-md px-md py-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-all duration-150 ease-in-out" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>dashboard</span>
<span className="font-label-md text-label-md">Overview</span>
</a>
<a className="flex items-center space-x-md px-md py-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-all duration-150 ease-in-out" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>inventory_2</span>
<span className="font-label-md text-label-md">Inventory</span>
</a>
<a className="flex items-center space-x-md px-md py-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-all duration-150 ease-in-out" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>shopping_cart</span>
<span className="font-label-md text-label-md">Orders</span>
</a>
<a className="flex items-center space-x-md px-md py-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-all duration-150 ease-in-out" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>group</span>
<span className="font-label-md text-label-md">Customers</span>
</a>
{/*  Active State (Determined by Intent: Settings & Security Page)  */}
<a className="flex items-center space-x-md px-md py-sm bg-surface-container-highest text-primary border-r-4 border-primary transition-all duration-150 ease-in-out" href="#">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1" }}>settings</span>
<span className="font-label-md text-label-md font-bold">Settings</span>
</a>
</nav>
</aside>
{/*  Main Content Wrapper  */}
<div className="ml-64 flex-1 flex flex-col min-w-0">
{/*  TopAppBar (from JSON)  */}
<header className="fixed top-0 right-0 left-64 z-40 border-b border-outline-variant bg-surface-container-lowest flex items-center justify-between px-6 h-16 transition-colors duration-200">
{/*  Search Bar (on_left)  */}
<div className="flex-1 max-w-[28rem] relative">
<span className="material-symbols-outlined absolute left-sm top-1/2 transform -translate-y-1/2 text-on-surface-variant">search</span>
<input className="w-full pl-[40px] pr-md py-sm bg-surface rounded border border-outline-variant focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-sm text-body-sm text-on-surface placeholder:text-on-surface-variant" placeholder="Search resources..." type="text" />
</div>
{/*  Trailing Icons  */}
<div className="flex items-center space-x-sm">
<button className="p-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-colors duration-200">
<span className="material-symbols-outlined">notifications</span>
</button>
<button className="p-sm rounded text-on-surface-variant hover:bg-surface-container hover:text-on-surface transition-colors duration-200">
<span className="material-symbols-outlined">help</span>
</button>
<button className="p-sm rounded text-primary hover:bg-surface-container transition-colors duration-200">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 1" }}>account_circle</span>
</button>
</div>
</header>
{/*  Page Content  */}
<main className="flex-1 pt-24 px-xl pb-xxl max-w-container-max mx-auto w-full">
<div className="mb-lg flex justify-between items-end">
<div>
<h1 className="font-h1 text-h1 text-on-surface">Settings &amp; Security</h1>
<p className="font-body-md text-body-md text-on-surface-variant mt-xs">Manage your store profile, integrations, and access control.</p>
</div>
<button className="px-lg py-sm bg-primary text-on-primary font-label-md text-label-md rounded hover:bg-surface-tint transition-colors">
                    Save All Changes
                </button>
</div>
<div className="grid grid-cols-1 lg:grid-cols-3 gap-lg">
{/*  Left Column: Forms  */}
<div className="lg:col-span-2 space-y-lg">
{/*  Store Profile Card  */}
<section className="bg-surface-container-lowest border border-outline-variant rounded p-lg">
<div className="mb-md border-b border-outline-variant pb-sm">
<h2 className="font-h3 text-h3 text-on-surface">Store Profile</h2>
<p className="font-body-sm text-body-sm text-on-surface-variant">Public-facing information displayed on receipts and storefront.</p>
</div>
<div className="grid grid-cols-1 md:grid-cols-2 gap-md">
<div className="md:col-span-2">
<label className="font-label-md text-label-md text-on-surface">Store Name</label>
<input className="w-full mt-xs px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface" type="text" value="Gojek Marketplace Central" />
</div>
<div>
<label className="font-label-md text-label-md text-on-surface">Support Email</label>
<input className="w-full mt-xs px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface" type="email" value="support@example.com" />
</div>
<div>
<label className="font-label-md text-label-md text-on-surface">Support Phone</label>
<input className="w-full mt-xs px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface" type="tel" value="+62 812 3456 7890" />
</div>
<div className="md:col-span-2">
<label className="font-label-md text-label-md text-on-surface">Business Address</label>
<textarea className="w-full mt-xs px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface resize-none" rows={3}>Jl. Sudirman No. 123, Jakarta Selatan, 12190</textarea>
</div>
</div>
</section>
{/*  Payment Gateway Card  */}
<section className="bg-surface-container-lowest border border-outline-variant rounded p-lg">
<div className="mb-md border-b border-outline-variant pb-sm flex justify-between items-center">
<div>
<h2 className="font-h3 text-h3 text-on-surface">Payment Gateway</h2>
<p className="font-body-sm text-body-sm text-on-surface-variant">Midtrans integration keys for processing transactions.</p>
</div>
<span className="px-sm py-xs bg-surface-container-highest text-primary font-label-sm text-label-sm rounded uppercase tracking-wider">Connected</span>
</div>
<div className="space-y-md">
<div>
<label className="font-label-md text-label-md text-on-surface">Merchant ID</label>
<div className="flex mt-xs">
<input className="w-full px-md py-[10px] bg-surface border border-outline-variant rounded-l focus:outline-none font-body-md text-body-md text-on-surface-variant" disabled type="text" value="G73829102" />
<button className="px-md border border-l-0 border-outline-variant rounded-r bg-surface-container hover:bg-surface-container-highest text-on-surface-variant transition-colors flex items-center justify-center">
<span className="material-symbols-outlined text-[20px]">content_copy</span>
</button>
</div>
</div>
<div>
<label className="font-label-md text-label-md text-on-surface flex justify-between">
                                    Client Key
                                    <span className="font-body-sm text-body-sm text-on-surface-variant font-normal">Publicly exposed</span>
</label>
<div className="flex mt-xs">
<input className="w-full px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded-l focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface" type="password" value="SB-Mid-client-xxxxxxxxxxxxx" />
<button className="px-md border border-l-0 border-outline-variant rounded-r bg-surface-container hover:bg-surface-container-highest text-on-surface-variant transition-colors flex items-center justify-center">
<span className="material-symbols-outlined text-[20px]">visibility</span>
</button>
</div>
</div>
<div>
<label className="font-label-md text-label-md text-on-surface flex justify-between">
                                    Server Key
                                    <span className="font-label-sm text-error font-normal bg-error-container px-xs rounded">Keep Secret</span>
</label>
<div className="flex mt-xs">
<input className="w-full px-md py-[10px] bg-surface-container-lowest border border-outline-variant rounded-l focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary font-body-md text-body-md text-on-surface" type="password" value="SB-Mid-server-xxxxxxxxxxxxxxxxxxxxx" />
<button className="px-md border border-l-0 border-outline-variant rounded-r bg-surface-container hover:bg-surface-container-highest text-on-surface-variant transition-colors flex items-center justify-center">
<span className="material-symbols-outlined text-[20px]">visibility</span>
</button>
</div>
</div>
</div>
</section>
</div>
{/*  Right Column: RBAC  */}
<div className="lg:col-span-1">
<section className="bg-surface-container-lowest border border-outline-variant rounded p-lg sticky top-24">
<div className="mb-md border-b border-outline-variant pb-sm">
<h2 className="font-h3 text-h3 text-on-surface">RBAC Roles</h2>
<p className="font-body-sm text-body-sm text-on-surface-variant">Global permission toggles.</p>
</div>
<div className="space-y-md">
{/*  Role Toggle Item  */}
<div className="flex items-center justify-between py-sm">
<div>
<div className="font-label-md text-label-md text-on-surface">Administrator</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Full system access</div>
</div>
<label className="relative inline-flex items-center cursor-pointer">
<input checked className="sr-only peer" type="checkbox" />
<div className="w-11 h-6 bg-surface-dim peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-secondary rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-outline-variant after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
</label>
</div>
<hr className="border-t border-outline-variant" />
{/*  Role Toggle Item  */}
<div className="flex items-center justify-between py-sm">
<div>
<div className="font-label-md text-label-md text-on-surface">Inventory Manager</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Create/edit products</div>
</div>
<label className="relative inline-flex items-center cursor-pointer">
<input checked className="sr-only peer" type="checkbox" />
<div className="w-11 h-6 bg-surface-dim peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-secondary rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-outline-variant after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
</label>
</div>
<hr className="border-t border-outline-variant" />
{/*  Role Toggle Item  */}
<div className="flex items-center justify-between py-sm">
<div>
<div className="font-label-md text-label-md text-on-surface">Customer Support</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">View orders &amp; users</div>
</div>
<label className="relative inline-flex items-center cursor-pointer">
<input checked className="sr-only peer" type="checkbox" />
<div className="w-11 h-6 bg-surface-dim peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-secondary rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-outline-variant after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
</label>
</div>
<hr className="border-t border-outline-variant" />
{/*  Role Toggle Item  */}
<div className="flex items-center justify-between py-sm">
<div>
<div className="font-label-md text-label-md text-on-surface">Read-Only Analyst</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">Dashboard metrics only</div>
</div>
<label className="relative inline-flex items-center cursor-pointer">
<input className="sr-only peer" type="checkbox" />
<div className="w-11 h-6 bg-surface-dim peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-secondary rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-outline-variant after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
</label>
</div>
</div>
<div className="mt-lg pt-md border-t border-outline-variant">
<button className="w-full py-[10px] border border-outline-variant bg-surface-container-lowest text-secondary font-label-md text-label-md rounded hover:bg-surface-container transition-colors flex items-center justify-center space-x-xs">
<span className="material-symbols-outlined text-[20px]">add</span>
<span>Create Custom Role</span>
</button>
</div>
</section>
</div>
</div>
</main>
</div>
    </div>
  );
}
