/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/inventory_management/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
import Link from "next/link";

import { listAdminProducts } from "@/lib/products";

// Page hits the database on every request — opt out of static prerender.
export const dynamic = "force-dynamic";

const fmt = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2 });

export default async function Page() {
  const products = await listAdminProducts();
  return (
    <div className={`theme-admin bg-background text-on-background font-body-md antialiased flex h-screen overflow-hidden`}>
{/*  SideNavBar  */}
<aside className="bg-surface-container-lowest h-screen w-64 flex flex-col border-r border-outline-variant z-50 transition-all duration-150 ease-in-out shrink-0">
<div className="px-6 py-4">
<h1 className="font-h3 text-h3 font-black tracking-tight text-on-surface">AdminConsole</h1>
<p className="font-label-sm text-label-sm text-on-surface-variant">Enterprise Suite</p>
</div>
<nav className="flex flex-col flex-1 py-4 space-y-1 overflow-y-auto px-sm">
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container-low transition-colors duration-200" href="#">
<span className="material-symbols-outlined" data-icon="dashboard">dashboard</span>
<span className="font-label-md text-label-md">Overview</span>
</a>
<a className="flex items-center gap-md px-md py-sm bg-surface-container text-primary border-r-[4px] border-primary transition-colors duration-200" href="#">
<span className="material-symbols-outlined" data-icon="inventory_2" style={{ fontVariationSettings: "'FILL' 1" }}>inventory_2</span>
<span className="font-label-md text-label-md">Inventory</span>
</a>
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container-low transition-colors duration-200" href="#">
<span className="material-symbols-outlined" data-icon="shopping_cart">shopping_cart</span>
<span className="font-label-md text-label-md">Orders</span>
</a>
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container-low transition-colors duration-200" href="#">
<span className="material-symbols-outlined" data-icon="group">group</span>
<span className="font-label-md text-label-md">Customers</span>
</a>
<a className="flex items-center gap-md px-md py-sm rounded-lg text-on-surface-variant hover:bg-surface-container-low transition-colors duration-200 mt-auto" href="#">
<span className="material-symbols-outlined" data-icon="settings">settings</span>
<span className="font-label-md text-label-md">Settings</span>
</a>
</nav>
</aside>
{/*  Main Content Wrapper  */}
<div className="flex-1 flex flex-col min-w-0">
{/*  TopAppBar  */}
<header className="bg-surface-container-lowest border-b border-outline-variant h-[64px] flex items-center justify-between px-6 shrink-0 z-40 transition-colors duration-200 w-full">
<div className="flex items-center w-96">
<div className="relative w-full">
<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-body-lg" data-icon="search">search</span>
<input className="w-full pl-10 pr-4 py-sm bg-surface-container-low border border-outline-variant rounded text-body-sm text-on-surface focus:outline-none focus:border-secondary transition-colors h-[36px]" placeholder="Search across AdminPanel..." type="text" />
</div>
</div>
<div className="flex items-center gap-md text-on-surface-variant">
<button className="p-sm hover:bg-surface-container-low rounded-full transition-colors flex items-center justify-center">
<span className="material-symbols-outlined" data-icon="notifications">notifications</span>
</button>
<button className="p-sm hover:bg-surface-container-low rounded-full transition-colors flex items-center justify-center">
<span className="material-symbols-outlined" data-icon="help">help</span>
</button>
<button className="p-sm hover:bg-surface-container-low rounded-full transition-colors flex items-center justify-center ml-sm">
<span className="material-symbols-outlined" data-icon="account_circle">account_circle</span>
</button>
</div>
</header>
{/*  Page Canvas  */}
<main className="flex-1 overflow-y-auto bg-background p-lg lg:p-xl">
<div className="max-w-[1280px] mx-auto space-y-lg">
{/*  Page Header & Tabs  */}
<div className="flex flex-col gap-md mb-lg">
<div className="flex items-center justify-between">
<h1 className="font-h1 text-h1 text-on-surface">Inventory Management</h1>
<div className="flex gap-sm">
<button className="px-md py-sm bg-surface-container-lowest border border-outline-variant text-secondary font-label-md text-label-md rounded hover:bg-surface-container-low transition-colors flex items-center gap-xs">
<span className="material-symbols-outlined text-[18px]" data-icon="download">download</span>
                                Export
                            </button>
<Link href="/admin/inventory/new" className="px-md py-sm bg-primary text-on-primary font-label-md text-label-md rounded hover:bg-surface-tint transition-colors flex items-center gap-xs">
<span className="material-symbols-outlined text-[18px]" data-icon="add">add</span>
                                Add Product
                            </Link>
</div>
</div>
<div className="flex border-b border-outline-variant">
<button className="px-md py-sm border-b-[2px] border-primary text-primary font-label-md text-label-md">Products</button>
<button className="px-md py-sm border-b-[2px] border-transparent text-on-surface-variant hover:text-on-surface font-label-md text-label-md transition-colors">Stock Audit Log</button>
</div>
</div>
{/*  Bento Grid Summary Stats  */}
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-md">
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-md flex flex-col gap-sm">
<span className="font-label-sm text-label-sm text-on-surface-variant flex items-center gap-xs">
<span className="material-symbols-outlined text-[16px]" data-icon="inventory">inventory</span>
                            Total Products
                        </span>
<div className="font-h2 text-h2 text-on-surface">12,405</div>
</div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-md flex flex-col gap-sm">
<span className="font-label-sm text-label-sm text-on-surface-variant flex items-center gap-xs">
<span className="material-symbols-outlined text-[16px] text-error" data-icon="warning">warning</span>
                            Low Stock Alerts
                        </span>
<div className="font-h2 text-h2 text-on-surface">48</div>
</div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-md flex flex-col gap-sm">
<span className="font-label-sm text-label-sm text-on-surface-variant flex items-center gap-xs">
<span className="material-symbols-outlined text-[16px]" data-icon="category">category</span>
                            Active Categories
                        </span>
<div className="font-h2 text-h2 text-on-surface">156</div>
</div>
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-md flex flex-col gap-sm">
<span className="font-label-sm text-label-sm text-on-surface-variant flex items-center gap-xs">
<span className="material-symbols-outlined text-[16px]" data-icon="payments">payments</span>
                            Est. Inventory Value
                        </span>
<div className="font-h2 text-h2 text-on-surface">$1.2M</div>
</div>
</div>
{/*  Robust Data Table Card  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg flex flex-col overflow-hidden">
{/*  Table Toolbar  */}
<div className="p-md border-b border-outline-variant flex items-center justify-between bg-surface-bright">
<div className="flex items-center gap-sm w-full max-w-[28rem]">
<div className="relative w-full">
<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-[18px]" data-icon="search">search</span>
<input className="w-full pl-9 pr-4 py-xs bg-surface-container-lowest border border-outline-variant rounded text-body-sm text-on-surface focus:outline-none focus:border-secondary transition-colors h-[32px]" placeholder="Search by SKU, Name, or Category" type="text" />
</div>
</div>
<div className="flex items-center gap-sm">
<button className="px-sm py-xs bg-surface-container-lowest border border-outline-variant text-on-surface-variant font-label-sm text-label-sm rounded hover:bg-surface-container-low transition-colors flex items-center gap-xs h-[32px]">
<span className="material-symbols-outlined text-[16px]" data-icon="filter_list">filter_list</span>
                                Filter
                            </button>
<button className="px-sm py-xs bg-surface-container-lowest border border-outline-variant text-on-surface-variant font-label-sm text-label-sm rounded hover:bg-surface-container-low transition-colors flex items-center gap-xs h-[32px]">
<span className="material-symbols-outlined text-[16px]" data-icon="view_column">view_column</span>
                                Columns
                            </button>
</div>
</div>
{/*  Table Wrapper for horizontal scroll if needed  */}
<div className="overflow-x-auto">
<table className="w-full text-left border-collapse">
<thead>
<tr className="border-b border-outline-variant bg-surface-bright">
<th className="p-md w-12 text-center align-middle">
<input className="rounded border-outline-variant text-primary focus:ring-primary w-4 h-4" type="checkbox" />
</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold">Product Info</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold">SKU</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold">Category</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold text-right">Unit Price</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold text-right">Stock</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold text-center">Status</th>
<th className="p-md font-label-sm text-label-sm text-on-surface-variant font-semibold text-right">Actions</th>
</tr>
</thead>
<tbody className="divide-y divide-outline-variant">
{products.length === 0 ? (
<tr><td className="p-md text-center text-on-surface-variant" colSpan={8}>Belum ada produk. Klik “New Product” untuk menambahkan.</td></tr>
) : products.map((product) => (
<tr key={product.id} className="hover:bg-surface-container-low transition-colors">
<td className="p-md text-center align-middle">
<input className="rounded border-outline-variant text-primary focus:ring-primary w-4 h-4" type="checkbox" />
</td>
<td className="p-md">
<div className="flex items-center gap-md">
<div className="w-10 h-10 rounded border border-outline-variant bg-surface-container flex-shrink-0 flex items-center justify-center overflow-hidden">
{product.primaryImageUrl ? (<img alt={product.name} className="w-full h-full object-cover" src={product.primaryImageUrl} />) : (<span className="material-symbols-outlined text-on-surface-variant text-[18px]">image</span>)}
</div>
<div className="flex flex-col">
<span className="font-label-md text-label-md text-on-surface">{product.name}</span>
<span className="font-body-sm text-body-sm text-on-surface-variant">{product.slug}</span>
</div>
</div>
</td>
<td className="p-md font-body-sm text-body-sm text-on-surface font-mono">{product.id.slice(0, 12).toUpperCase()}</td>
<td className="p-md font-body-sm text-body-sm text-on-surface">{product.category?.name ?? "—"}</td>
<td className="p-md font-body-sm text-body-sm text-on-surface text-right">{fmt.format(product.price)}</td>
<td className="p-md font-body-sm text-body-sm text-on-surface text-right">{product.stock}</td>
<td className="p-md text-center">
<span className={`inline-flex items-center px-2 py-0.5 rounded font-label-sm text-label-sm border ${product.status === "ACTIVE" ? "bg-secondary-container text-on-secondary-container border-secondary-fixed-dim" : product.status === "DRAFT" ? "bg-surface-container text-on-surface border-outline-variant" : "bg-error-container text-on-error-container border-error-container"}`}>{product.status}</span>
</td>
<td className="p-md text-right">
<div className="flex items-center justify-end gap-sm">
<Link className="p-xs text-on-surface-variant hover:text-secondary transition-colors" href={`/admin/inventory/${product.id}`} title="Edit">
<span className="material-symbols-outlined text-[18px]">edit</span>
</Link>
</div>
</td>
</tr>
))}
</tbody>
</table>
</div>
{/*  Pagination  */}
<div className="p-sm px-md border-t border-outline-variant bg-surface-bright flex items-center justify-between">
<span className="font-body-sm text-body-sm text-on-surface-variant">Showing 1 to 4 of 12,405 entries</span>
<div className="flex items-center gap-xs">
<button className="px-sm py-xs border border-outline-variant rounded bg-surface-container-lowest text-on-surface-variant hover:bg-surface-container-low disabled:opacity-50" disabled>
<span className="material-symbols-outlined text-[18px]" data-icon="chevron_left">chevron_left</span>
</button>
<button className="w-8 h-8 flex items-center justify-center border border-primary bg-primary text-on-primary rounded font-label-sm text-label-sm">1</button>
<button className="w-8 h-8 flex items-center justify-center border border-outline-variant bg-surface-container-lowest text-on-surface rounded font-label-sm text-label-sm hover:bg-surface-container-low">2</button>
<button className="w-8 h-8 flex items-center justify-center border border-outline-variant bg-surface-container-lowest text-on-surface rounded font-label-sm text-label-sm hover:bg-surface-container-low">3</button>
<span className="text-on-surface-variant px-1">...</span>
<button className="px-sm py-xs border border-outline-variant rounded bg-surface-container-lowest text-on-surface-variant hover:bg-surface-container-low">
<span className="material-symbols-outlined text-[18px]" data-icon="chevron_right">chevron_right</span>
</button>
</div>
</div>
</div>
</div>
</main>
</div>
    </div>
  );
}
