/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/admin_overview/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
import { SignOutButton } from "@/app/(auth)/sign-out-button";

export default function Page() {
  return (
    <div className={`theme-admin bg-surface font-body-md text-on-surface antialiased overflow-hidden flex h-screen`}>
{/*  SideNavBar (Shared Component)  */}
<nav className="h-screen w-64 fixed left-0 top-0 z-50 bg-surface-container-lowest border-r border-outline-variant flex flex-col transition-all duration-150 ease-in-out">
{/*  Header  */}
<div className="px-6 py-4 border-b border-outline-variant">
<h1 className="text-lg font-black tracking-tight text-on-surface">AdminConsole</h1>
<p className="font-body-sm text-body-sm text-on-surface-variant mt-1">Enterprise Suite</p>
</div>
{/*  Navigation Links  */}
<div className="flex flex-col flex-1 py-4 space-y-1 overflow-y-auto">
{/*  Active Tab: Overview  */}
<a className="flex items-center px-6 py-3 bg-surface-container text-primary border-r-4 border-primary font-label-md text-label-md transition-colors duration-200" href="#">
<span className="material-symbols-outlined mr-4" style={{ fontVariationSettings: "'FILL' 1" }}>dashboard</span>
                Overview
            </a>
{/*  Inactive Tabs  */}
<a className="flex items-center px-6 py-3 text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low font-label-md text-label-md transition-colors duration-200" href="#">
<span className="material-symbols-outlined mr-4">inventory_2</span>
                Inventory
            </a>
<a className="flex items-center px-6 py-3 text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low font-label-md text-label-md transition-colors duration-200" href="#">
<span className="material-symbols-outlined mr-4">shopping_cart</span>
                Orders
            </a>
<a className="flex items-center px-6 py-3 text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low font-label-md text-label-md transition-colors duration-200" href="#">
<span className="material-symbols-outlined mr-4">group</span>
                Customers
            </a>
<a className="flex items-center px-6 py-3 text-on-surface-variant hover:text-on-surface hover:bg-surface-container-low font-label-md text-label-md transition-colors duration-200" href="#">
<span className="material-symbols-outlined mr-4">settings</span>
                Settings
            </a>
</div>
{/*  Bottom User Area  */}
<div className="p-4 border-t border-outline-variant">
<div className="flex items-center">
<img alt="Admin Profile" className="w-10 h-10 rounded-full border border-outline-variant" data-alt="close up portrait of a professional man in a dark suit with a neutral background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCfFSQahGf_tcZlWR9RaYAX_e07ut_-dsZ6i2CGmvleWDXPNeWKTpzwVWwz3qsFQgIeY1AoJ5zc0tm7tBlisowgw3vlZRSCzAwDAUYs_Hap2vO1bpSJCVNqGKU35onjNk1LQWMmjtP5encXQMQ2o7f8SwAyf004R2bQ-iS9t807iwG8eWgewu44e7ebRBmtn31ZlL8g2M3JabNE-YfqIYMzArXw7KGCchZsvX9Q0PeCI0Nd6yH6j8f0FNriPRZggnLYut4r4rkWiSuz" />
<div className="ml-3">
<p className="font-label-sm text-label-sm text-on-surface">J. Doe</p>
<p className="font-body-sm text-body-sm text-on-surface-variant text-[11px]">System Admin</p>
</div>
</div>
<SignOutButton className="font-body-sm text-body-sm text-on-surface-variant hover:text-on-surface flex items-center gap-2 mt-3 w-full" label="Sign out" />
</div>
</nav>
{/*  Main Content Wrapper  */}
<div className="flex-1 flex flex-col ml-64 h-screen relative">
{/*  TopAppBar (Shared Component)  */}
<header className="fixed top-0 right-0 left-64 z-40 bg-surface-container-lowest border-b border-outline-variant flex items-center justify-between px-6 h-16 transition-colors duration-200">
{/*  Left: Search  */}
<div className="flex-1 flex items-center">
<h2 className="font-h3 text-h3 text-primary mr-8 hidden md:block">AdminPanel</h2>
<div className="relative w-full max-w-[28rem]">
<span className="material-symbols-outlined absolute left-3 top-1/2 transform -translate-y-1/2 text-on-surface-variant">search</span>
<input className="w-full pl-10 pr-4 py-2 bg-surface border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary text-on-surface placeholder-on-surface-variant" placeholder="Search orders, inventory, or customers..." type="text" />
</div>
</div>
{/*  Right: Actions  */}
<div className="flex items-center space-x-2 ml-4">
<button aria-label="Notifications" className="p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container-low rounded-DEFAULT transition-colors duration-200">
<span className="material-symbols-outlined">notifications</span>
</button>
<button aria-label="Help" className="p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container-low rounded-DEFAULT transition-colors duration-200">
<span className="material-symbols-outlined">help</span>
</button>
<button aria-label="Account" className="p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container-low rounded-DEFAULT transition-colors duration-200">
<span className="material-symbols-outlined">account_circle</span>
</button>
</div>
</header>
{/*  Dashboard Canvas  */}
<main className="flex-1 mt-16 p-lg overflow-y-auto w-full max-w-container-max mx-auto">
{/*  Page Header  */}
<div className="mb-lg flex justify-between items-end">
<div>
<h1 className="font-h1 text-h1 text-on-surface tracking-tight">Overview</h1>
<p className="font-body-md text-body-md text-on-surface-variant mt-1">Real-time metrics and system alerts.</p>
</div>
<div className="flex space-x-3">
<button className="px-4 py-2 bg-surface-container-lowest border border-outline-variant text-on-surface font-label-md text-label-md rounded-DEFAULT hover:bg-surface-container-low flex items-center">
<span className="material-symbols-outlined mr-2 text-[18px]">calendar_today</span>
                        Last 30 Days
                    </button>
<button className="px-4 py-2 bg-primary text-on-primary font-label-md text-label-md rounded-DEFAULT hover:bg-surface-tint flex items-center transition-colors">
<span className="material-symbols-outlined mr-2 text-[18px]">download</span>
                        Export
                    </button>
</div>
</div>
{/*  Stats Widgets (Bento Grid)  */}
<div className="grid grid-cols-1 md:grid-cols-3 gap-md mb-lg">
{/*  Stat Card 1  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col justify-between">
<div className="flex justify-between items-start mb-4">
<div className="p-2 bg-primary-container/10 rounded-DEFAULT">
<span className="material-symbols-outlined text-primary">payments</span>
</div>
<span className="inline-flex items-center px-2 py-0.5 rounded-DEFAULT text-[12px] font-bold bg-primary-container text-on-primary-container">
<span className="material-symbols-outlined text-[14px] mr-1">trending_up</span>
                            +12.5%
                        </span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface-variant">Total Revenue</p>
<h3 className="font-h2 text-h2 text-on-surface mt-1">$124,500.00</h3>
</div>
</div>
{/*  Stat Card 2  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col justify-between">
<div className="flex justify-between items-start mb-4">
<div className="p-2 bg-secondary-container/10 rounded-DEFAULT">
<span className="material-symbols-outlined text-secondary-container">shopping_bag</span>
</div>
<span className="inline-flex items-center px-2 py-0.5 rounded-DEFAULT text-[12px] font-bold bg-primary-container text-on-primary-container">
<span className="material-symbols-outlined text-[14px] mr-1">trending_up</span>
                            +5.2%
                        </span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface-variant">Total Orders</p>
<h3 className="font-h2 text-h2 text-on-surface mt-1">1,842</h3>
</div>
</div>
{/*  Stat Card 3  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-md flex flex-col justify-between">
<div className="flex justify-between items-start mb-4">
<div className="p-2 bg-tertiary-container/10 rounded-DEFAULT">
<span className="material-symbols-outlined text-tertiary-container">group</span>
</div>
<span className="inline-flex items-center px-2 py-0.5 rounded-DEFAULT text-[12px] font-bold bg-surface-container text-on-surface-variant">
<span className="material-symbols-outlined text-[14px] mr-1">trending_flat</span>
                            0.0%
                        </span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface-variant">Active Customers</p>
<h3 className="font-h2 text-h2 text-on-surface mt-1">8,409</h3>
</div>
</div>
</div>
{/*  Main Content Grid  */}
<div className="grid grid-cols-1 lg:grid-cols-3 gap-lg">
{/*  Recent Orders Data Table (Takes 2 columns)  */}
<div className="lg:col-span-2 bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden flex flex-col">
<div className="px-lg py-md border-b border-outline-variant flex justify-between items-center">
<h3 className="font-h3 text-h3 text-on-surface">Recent Orders</h3>
<a className="font-label-md text-label-md text-secondary hover:text-secondary-container transition-colors" href="#">View All</a>
</div>
<div className="overflow-x-auto">
<table className="w-full text-left border-collapse">
<thead>
<tr className="bg-surface font-label-sm text-label-sm text-on-surface-variant border-b border-outline-variant">
<th className="px-lg py-3 font-semibold">Order ID</th>
<th className="px-lg py-3 font-semibold">Customer</th>
<th className="px-lg py-3 font-semibold">Date</th>
<th className="px-lg py-3 font-semibold">Amount</th>
<th className="px-lg py-3 font-semibold">Status</th>
</tr>
</thead>
<tbody className="font-body-sm text-body-sm text-on-surface">
<tr className="border-b border-outline-variant hover:bg-surface-container-low transition-colors">
<td className="px-lg py-4 font-mono">#ORD-9021</td>
<td className="px-lg py-4">Sarah Jenkins</td>
<td className="px-lg py-4 text-on-surface-variant">Today, 10:42 AM</td>
<td className="px-lg py-4 font-semibold">$349.00</td>
<td className="px-lg py-4">
<span className="inline-flex items-center px-2 py-1 rounded-DEFAULT text-[11px] font-bold uppercase tracking-wider bg-surface-container-high text-on-surface">Processing</span>
</td>
</tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-low transition-colors">
<td className="px-lg py-4 font-mono">#ORD-9020</td>
<td className="px-lg py-4">Michael Chen</td>
<td className="px-lg py-4 text-on-surface-variant">Today, 09:15 AM</td>
<td className="px-lg py-4 font-semibold">$1,299.50</td>
<td className="px-lg py-4">
<span className="inline-flex items-center px-2 py-1 rounded-DEFAULT text-[11px] font-bold uppercase tracking-wider bg-primary-container/20 text-primary">Shipped</span>
</td>
</tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-low transition-colors">
<td className="px-lg py-4 font-mono">#ORD-9019</td>
<td className="px-lg py-4">Emma Watson</td>
<td className="px-lg py-4 text-on-surface-variant">Yesterday, 04:30 PM</td>
<td className="px-lg py-4 font-semibold">$89.99</td>
<td className="px-lg py-4">
<span className="inline-flex items-center px-2 py-1 rounded-DEFAULT text-[11px] font-bold uppercase tracking-wider bg-primary-container/20 text-primary">Shipped</span>
</td>
</tr>
<tr className="border-b border-outline-variant hover:bg-surface-container-low transition-colors">
<td className="px-lg py-4 font-mono">#ORD-9018</td>
<td className="px-lg py-4">David Rodriguez</td>
<td className="px-lg py-4 text-on-surface-variant">Yesterday, 02:10 PM</td>
<td className="px-lg py-4 font-semibold">$450.00</td>
<td className="px-lg py-4">
<span className="inline-flex items-center px-2 py-1 rounded-DEFAULT text-[11px] font-bold uppercase tracking-wider bg-error-container/50 text-error">Failed</span>
</td>
</tr>
<tr className="hover:bg-surface-container-low transition-colors">
<td className="px-lg py-4 font-mono">#ORD-9017</td>
<td className="px-lg py-4">Global Tech LLC</td>
<td className="px-lg py-4 text-on-surface-variant">Oct 24, 2023</td>
<td className="px-lg py-4 font-semibold">$5,400.00</td>
<td className="px-lg py-4">
<span className="inline-flex items-center px-2 py-1 rounded-DEFAULT text-[11px] font-bold uppercase tracking-wider bg-surface-container text-on-surface-variant">Delivered</span>
</td>
</tr>
</tbody>
</table>
</div>
</div>
{/*  Low Stock Alerts Card (Takes 1 column)  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-xl flex flex-col">
<div className="px-lg py-md border-b border-outline-variant flex justify-between items-center bg-error-container/10">
<div className="flex items-center">
<span className="material-symbols-outlined text-error mr-2" style={{ fontVariationSettings: "'FILL' 1" }}>warning</span>
<h3 className="font-h3 text-h3 text-on-surface">Low Stock</h3>
</div>
<span className="bg-error text-on-error px-2 py-0.5 rounded-full font-label-sm text-[10px]">4</span>
</div>
<div className="flex-1 p-lg space-y-4">
{/*  Alert Item  */}
<div className="flex items-center justify-between">
<div className="flex items-center space-x-3">
<div className="w-10 h-10 bg-surface rounded-DEFAULT flex items-center justify-center border border-outline-variant">
<span className="material-symbols-outlined text-on-surface-variant text-[20px]">inventory_2</span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface leading-tight">Ergonomic Chair</p>
<p className="font-body-sm text-[12px] text-on-surface-variant">SKU: CHR-092</p>
</div>
</div>
<div className="text-right">
<p className="font-h3 text-h3 text-error leading-tight">2</p>
<p className="font-body-sm text-[11px] text-on-surface-variant">Left</p>
</div>
</div>
{/*  Alert Item  */}
<div className="flex items-center justify-between">
<div className="flex items-center space-x-3">
<div className="w-10 h-10 bg-surface rounded-DEFAULT flex items-center justify-center border border-outline-variant">
<span className="material-symbols-outlined text-on-surface-variant text-[20px]">inventory_2</span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface leading-tight">Wireless Mouse Pro</p>
<p className="font-body-sm text-[12px] text-on-surface-variant">SKU: MSE-881</p>
</div>
</div>
<div className="text-right">
<p className="font-h3 text-h3 text-error leading-tight">5</p>
<p className="font-body-sm text-[11px] text-on-surface-variant">Left</p>
</div>
</div>
{/*  Alert Item  */}
<div className="flex items-center justify-between">
<div className="flex items-center space-x-3">
<div className="w-10 h-10 bg-surface rounded-DEFAULT flex items-center justify-center border border-outline-variant">
<span className="material-symbols-outlined text-on-surface-variant text-[20px]">inventory_2</span>
</div>
<div>
<p className="font-label-md text-label-md text-on-surface leading-tight">USB-C Hub Gen 2</p>
<p className="font-body-sm text-[12px] text-on-surface-variant">SKU: HUB-204</p>
</div>
</div>
<div className="text-right">
<p className="font-h3 text-h3 text-error leading-tight">8</p>
<p className="font-body-sm text-[11px] text-on-surface-variant">Left</p>
</div>
</div>
</div>
<div className="p-4 border-t border-outline-variant bg-surface-bright">
<button className="w-full py-2 bg-surface-container-lowest border border-outline-variant text-on-surface font-label-md text-label-md rounded-DEFAULT hover:bg-surface-container-low transition-colors">
                            Manage Inventory
                        </button>
</div>
</div>
</div>
</main>
</div>
    </div>
  );
}
