/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/checkout_process/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
export default function Page() {
  return (
    <div className={`bg-surface-container-low text-on-surface antialiased font-body-md min-h-screen flex flex-col`}>
{/*  Minimal Header for Transactional Page  */}
<header className="bg-surface-container-lowest border-b border-outline-variant sticky top-0 z-50">
<div className="max-w-[1440px] mx-auto px-6 h-16 flex items-center justify-between">
<div className="text-xl font-black text-on-background tracking-tight">EnterpriseStore</div>
<div className="flex items-center gap-2 text-secondary font-body-sm">
<span className="material-symbols-outlined icon-fill text-sm">lock</span>
<span>Secure Checkout</span>
</div>
</div>
</header>
{/*  Main Content  */}
<main className="flex-grow max-w-[1440px] mx-auto w-full px-6 py-8">
<div className="mb-6">
<h1 className="font-h1 text-h1 text-on-background">Checkout</h1>
</div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-card-gap items-start">
{/*  Left Column: Multi-Step Form  */}
<div className="lg:col-span-8 space-y-card-gap">
{/*  Step 1: Shipping Address  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-container-padding">
<div className="flex items-center gap-3 mb-6 pb-4 border-b border-surface-variant">
<div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary text-on-primary font-h2 text-h2">1</div>
<h2 className="font-h2 text-h2 text-on-surface">Shipping Address</h2>
</div>
<form className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-5">
<div className="col-span-1">
<label className="block font-body-sm text-body-sm text-on-surface-variant mb-1 font-medium">First Name</label>
<input className="w-full bg-surface-container-lowest border border-outline-variant rounded px-3 py-2 text-body-md font-body-md text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-shadow" type="text" value="Alex" />
</div>
<div className="col-span-1">
<label className="block font-body-sm text-body-sm text-on-surface-variant mb-1 font-medium">Last Name</label>
<input className="w-full bg-surface-container-lowest border border-outline-variant rounded px-3 py-2 text-body-md font-body-md text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-shadow" type="text" value="Rivers" />
</div>
<div className="col-span-1 md:col-span-2">
<label className="block font-body-sm text-body-sm text-on-surface-variant mb-1 font-medium">Address Line 1</label>
<input className="w-full bg-surface-container-lowest border border-outline-variant rounded px-3 py-2 text-body-md font-body-md text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-shadow" type="text" value="123 Enterprise Parkway, Suite 400" />
</div>
<div className="col-span-1">
<label className="block font-body-sm text-body-sm text-on-surface-variant mb-1 font-medium">City</label>
<input className="w-full bg-surface-container-lowest border border-outline-variant rounded px-3 py-2 text-body-md font-body-md text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-shadow" type="text" value="Tech Hub" />
</div>
<div className="col-span-1">
<label className="block font-body-sm text-body-sm text-on-surface-variant mb-1 font-medium">Postal Code</label>
<input className="w-full bg-surface-container-lowest border border-outline-variant rounded px-3 py-2 text-body-md font-body-md text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-shadow" type="text" value="90210" />
</div>
<div className="col-span-1 md:col-span-2 mt-2">
<button className="bg-surface-container text-on-surface font-body-md text-body-md font-medium px-4 py-2 rounded border border-outline-variant hover:bg-surface-variant transition-colors" type="button">Save Address</button>
</div>
</form>
</div>
{/*  Step 2: Shipping Method  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-container-padding">
<div className="flex items-center gap-3 mb-6 pb-4 border-b border-surface-variant">
<div className="flex items-center justify-center w-8 h-8 rounded-full border-2 border-outline-variant text-outline font-h2 text-h2">2</div>
<h2 className="font-h2 text-h2 text-on-surface">Shipping Method</h2>
</div>
<div className="space-y-3">
{/*  Option 1: Selected  */}
<label className="flex items-start gap-4 p-4 rounded border-2 border-primary bg-primary-fixed cursor-pointer transition-colors">
<div className="flex-shrink-0 mt-0.5">
<input checked className="w-4 h-4 text-primary focus:ring-primary border-outline-variant" name="shipping" type="radio" />
</div>
<div className="flex-grow">
<div className="flex justify-between items-center mb-1">
<span className="font-h2 text-body-md font-semibold text-on-background">Raja Ongkir - JNE REG</span>
<span className="font-data-tabular text-data-tabular text-on-background">$15.00</span>
</div>
<p className="font-body-sm text-body-sm text-on-surface-variant">Estimated delivery: 2-3 business days</p>
</div>
</label>
{/*  Option 2  */}
<label className="flex items-start gap-4 p-4 rounded border border-outline-variant hover:border-outline cursor-pointer transition-colors">
<div className="flex-shrink-0 mt-0.5">
<input className="w-4 h-4 text-primary focus:ring-primary border-outline-variant" name="shipping" type="radio" />
</div>
<div className="flex-grow">
<div className="flex justify-between items-center mb-1">
<span className="font-h2 text-body-md font-semibold text-on-background">Raja Ongkir - JNE YES</span>
<span className="font-data-tabular text-data-tabular text-on-background">$25.00</span>
</div>
<p className="font-body-sm text-body-sm text-on-surface-variant">Estimated delivery: 1 business day (Next Day)</p>
</div>
</label>
</div>
</div>
{/*  Step 3: Payment Method  */}
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-container-padding">
<div className="flex items-center gap-3 mb-6 pb-4 border-b border-surface-variant">
<div className="flex items-center justify-center w-8 h-8 rounded-full border-2 border-outline-variant text-outline font-h2 text-h2">3</div>
<h2 className="font-h2 text-h2 text-on-surface">Payment</h2>
</div>
<div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
{/*  Credit Card  */}
<label className="flex flex-col items-center justify-center p-4 rounded border border-outline-variant hover:border-outline cursor-pointer transition-colors text-center gap-2">
<input className="sr-only" name="payment" type="radio" />
<span className="material-symbols-outlined text-outline text-3xl">credit_card</span>
<span className="font-body-md text-body-md font-medium text-on-surface">Credit Card</span>
</label>
{/*  Midtrans Selected  */}
<label className="flex flex-col items-center justify-center p-4 rounded border-2 border-primary bg-primary-fixed cursor-pointer transition-colors text-center gap-2">
<input checked className="sr-only" name="payment" type="radio" />
<span className="material-symbols-outlined text-primary text-3xl icon-fill">account_balance_wallet</span>
<span className="font-body-md text-body-md font-medium text-on-background">Midtrans Gateway</span>
</label>
</div>
{/*  Selected Payment Details Area  */}
<div className="bg-surface-container-low p-4 rounded border border-surface-variant">
<p className="font-body-sm text-body-sm text-on-surface-variant mb-4">You will be redirected to the secure Midtrans payment portal to complete your transaction via Virtual Account, GoPay, or other supported methods.</p>
<div className="flex items-center gap-2 text-on-surface-variant">
<span className="material-symbols-outlined text-sm">verified_user</span>
<span className="font-label-caps text-label-caps uppercase">Secure Transaction</span>
</div>
</div>
</div>
</div>
{/*  Right Column: Order Summary  */}
<div className="lg:col-span-4">
<div className="bg-surface-container-lowest border border-outline-variant rounded-lg p-container-padding sticky top-24">
<h2 className="font-h2 text-h2 text-on-surface mb-6 pb-4 border-b border-surface-variant">Order Summary</h2>
{/*  Items  */}
<div className="space-y-4 mb-6 pb-6 border-b border-surface-variant">
{/*  Item 1  */}
<div className="flex gap-4">
<div className="w-16 h-16 rounded border border-outline-variant bg-surface overflow-hidden flex-shrink-0">
<img alt="Product" className="w-full h-full object-cover" data-alt="Sleek white smart watch with minimal face resting on a light grey surface" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBsDCgWsS230i1FJsA-o6zAp9GS-3wHXePdx7wRM3v2ZERus2i56vMco8hK8qmnlNi73YMOUdW_pqp_I8TBewly_WhGrkQ9VjlomNSREh-xKfaIZ1wv0uPtTdjEJ9ykGu7QgFq-V1R-G47yAHhr1TGTpe9-Mu9cUgHd_AFPP7zczKrtEUrzIGD3qKIwuko2qSvs4ZMk5rxpNQgU5wZdzXExEJpZhNmj3-LgMD3za1lXDigjmITh-I3DGZamsp5lP8D4Excz2hIDWK9U" />
</div>
<div className="flex-grow flex flex-col justify-between">
<div>
<h3 className="font-body-md text-body-md text-on-background font-medium line-clamp-1">Enterprise Smart Watch Pro</h3>
<p className="font-body-sm text-body-sm text-on-surface-variant">Qty: 1</p>
</div>
<div className="font-data-tabular text-data-tabular text-on-background text-right">$299.00</div>
</div>
</div>
{/*  Item 2  */}
<div className="flex gap-4">
<div className="w-16 h-16 rounded border border-outline-variant bg-surface overflow-hidden flex-shrink-0">
<img alt="Product" className="w-full h-full object-cover" data-alt="Premium black over-ear wireless headphones on a dark textured background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDio6yRagkav0kh1jhpWGUvFi39C8VyHpeFyyQemrvYJTIJRU-QNhK7y0bvTD6NM4HhnVKbfsM8xYztTE5RDJLZ068eFaw6e6COFsL-oQ-ijWlNUgymOYHtfGXk27VKuW7-MpSYQ2Y7oXASrIYY3uNmQGVkkxFEeRiBrt3ZnyqzkVUQ30txXl6gShoHrjB_yUvuNdRjRugFX4VEaFa9l2vlQDLsVXdzT2C9VUhWpnXvLHOkHNQxRkm_qWC1WmumxnruOkJEXsJzTklT" />
</div>
<div className="flex-grow flex flex-col justify-between">
<div>
<h3 className="font-body-md text-body-md text-on-background font-medium line-clamp-1">Noise Cancelling Headphones</h3>
<p className="font-body-sm text-body-sm text-on-surface-variant">Qty: 2</p>
</div>
<div className="font-data-tabular text-data-tabular text-on-background text-right">$398.00</div>
</div>
</div>
</div>
{/*  Calculations  */}
<div className="space-y-3 mb-6">
<div className="flex justify-between font-body-sm text-body-sm text-on-surface-variant">
<span>Subtotal</span>
<span className="font-data-tabular text-data-tabular text-on-background">$697.00</span>
</div>
<div className="flex justify-between font-body-sm text-body-sm text-on-surface-variant">
<span>Shipping (JNE REG)</span>
<span className="font-data-tabular text-data-tabular text-on-background">$15.00</span>
</div>
<div className="flex justify-between font-body-sm text-body-sm text-on-surface-variant">
<span>Tax (10%)</span>
<span className="font-data-tabular text-data-tabular text-on-background">$69.70</span>
</div>
</div>
{/*  Total  */}
<div className="flex justify-between items-center mb-8 pt-4 border-t border-surface-variant">
<span className="font-h2 text-h2 text-on-background">Total</span>
<span className="font-h1 text-h1 text-primary font-bold">$781.70</span>
</div>
{/*  Action  */}
<button className="w-full bg-primary hover:bg-on-primary-fixed-variant text-on-primary font-body-md text-body-md font-medium py-3 rounded transition-colors shadow-sm flex items-center justify-center gap-2">
<span className="material-symbols-outlined text-[20px]">lock</span>
                        Place Order via Midtrans
                    </button>
<p className="text-center font-body-sm text-body-sm text-on-surface-variant mt-4">
                        By placing your order, you agree to our Terms of Service and Privacy Policy.
                    </p>
</div>
</div>
</div>
</main>
    </div>
  );
}
