/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/user_profile/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
import { SignOutButton } from "@/app/(auth)/sign-out-button";

export default function Page() {
  return (
    <div className={`bg-background text-on-background font-body-md antialiased min-h-screen`}>
{/*  TopNavBar  */}
<header className="bg-surface-container-lowest border-b border-surface-variant fixed top-0 w-full z-50 flex justify-between items-center px-6 h-16 max-w-[1440px] mx-auto left-0 right-0">
<div className="flex items-center gap-8">
<div className="text-h1 font-h1 font-black text-on-background tracking-tighter">EnterpriseStore</div>
{/*  Search Bar (on_left)  */}
<div className="relative w-64 hidden md:block">
<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-outline-variant" style={{ fontSize: "18px" }}>search</span>
<input className="w-full pl-10 pr-4 py-1.5 bg-surface border border-outline-variant rounded focus:border-primary focus:ring-2 focus:ring-primary-fixed-dim outline-none font-body-sm text-body-sm transition-all text-on-background placeholder:text-outline" placeholder="Search..." type="text" />
</div>
</div>
<nav className="hidden md:flex items-center gap-6">
<a className="font-body-md text-body-md text-on-surface-variant hover:text-on-background hover:bg-surface-container-low transition-colors px-2 py-1 rounded" href="#">Shop</a>
<a className="font-body-md text-body-md text-on-surface-variant hover:text-on-background hover:bg-surface-container-low transition-colors px-2 py-1 rounded" href="#">Categories</a>
<a className="font-body-md text-body-md text-on-surface-variant hover:text-on-background hover:bg-surface-container-low transition-colors px-2 py-1 rounded" href="#">Deals</a>
<a className="font-body-md text-body-md text-on-surface-variant hover:text-on-background hover:bg-surface-container-low transition-colors px-2 py-1 rounded" href="#">Support</a>
</nav>
<div className="flex items-center gap-4">
<button className="text-on-surface-variant hover:text-on-background hover:bg-surface-container-low transition-colors p-2 rounded-full active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="shopping_cart">shopping_cart</span>
</button>
<button className="text-primary border-b-2 border-primary pb-1 p-2 rounded-none active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="account_circle" style={{ fontVariationSettings: "'FILL' 1" }}>account_circle</span>
</button>
</div>
</header>
{/*  App Layout Container  */}
<div className="flex max-w-[1440px] mx-auto pt-16 min-h-screen">
{/*  SideNavBar  */}
<aside className="w-64 bg-inverse-surface border-r border-outline flex-shrink-0 h-[calc(100vh-64px)] sticky top-16 hidden md:flex flex-col">
<div className="p-6 border-b border-outline/30 flex items-center gap-4">
<div className="w-10 h-10 rounded bg-primary-container flex items-center justify-center flex-shrink-0 overflow-hidden">
<img alt="User Avatar" className="w-full h-full object-cover" data-alt="close up portrait of professional man in corporate setting with neutral lighting" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAmMeAwlTzLnim49dDXrFdxrRaqSC-vBl7U8yA_rOz-k-slZ1MRzkhBFgf9nsdd_dZPtKaJrUDBvsqsQ-0cDu_F1SeMAfxfLL7Mlb6OlBjQJhofUoAjK1IJFaKr2QEP2PElTb3Y9AnhW_vKtCx6RcqNONfyY5xyqsKlpWiiYjWvaGIz2e3Km-Gur66OZN-jY4D1v9Ehae_tAWS9_sDwuZb-UT7hMdFOgqgJyj0_8TItAQsnidYsxWrGkBH6jrrwkQft8GdNH0rajLbd" />
</div>
<div>
<div className="text-inverse-on-surface font-h2 text-h2 font-bold leading-tight">Alex Rivers</div>
<div className="text-inverse-on-surface/70 font-body-sm text-body-sm mt-0.5">Premium Member</div>
</div>
</div>
<nav className="flex-1 py-4 flex flex-col gap-1">
<a className="font-body-sm text-body-sm flex items-center gap-3 bg-on-secondary-fixed text-inverse-on-surface border-l-4 border-primary px-4 py-3 active:bg-inverse-surface/80 transition-colors" href="#">
<span className="material-symbols-outlined" data-icon="grid_view" style={{ fontVariationSettings: "'FILL' 1" }}>grid_view</span>
                    Dashboard
                </a>
<a className="font-body-sm text-body-sm flex items-center gap-3 text-surface-variant px-4 py-3 hover:text-inverse-on-surface hover:bg-on-secondary-fixed hover:bg-on-secondary-fixed transition-all duration-200" href="#">
<span className="material-symbols-outlined" data-icon="package_2">package_2</span>
                    My Orders
                </a>
<a className="font-body-sm text-body-sm flex items-center gap-3 text-surface-variant px-4 py-3 hover:text-inverse-on-surface hover:bg-on-secondary-fixed hover:bg-on-secondary-fixed transition-all duration-200" href="#">
<span className="material-symbols-outlined" data-icon="favorite">favorite</span>
                    Wishlist
                </a>
<a className="font-body-sm text-body-sm flex items-center gap-3 text-surface-variant px-4 py-3 hover:text-inverse-on-surface hover:bg-on-secondary-fixed hover:bg-on-secondary-fixed transition-all duration-200" href="#">
<span className="material-symbols-outlined" data-icon="settings">settings</span>
                    Account Settings
                </a>
<a className="font-body-sm text-body-sm flex items-center gap-3 text-surface-variant px-4 py-3 hover:text-inverse-on-surface hover:bg-on-secondary-fixed hover:bg-on-secondary-fixed transition-all duration-200 mt-auto border-t border-outline/30 pt-4" href="#">
<span className="material-symbols-outlined" data-icon="contact_support">contact_support</span>
                    Support
                </a>
<SignOutButton />
</nav>
</aside>
{/*  Main Content Canvas  */}
<main className="flex-1 p-8 bg-background overflow-y-auto">
<div className="max-w-5xl mx-auto">
<header className="mb-8">
<h1 className="font-h1 text-h1 text-on-background">User Profile</h1>
<p className="font-body-md text-body-md text-on-surface-variant mt-1">Manage your account details and track recent activity.</p>
</header>
{/*  Local Tab System  */}
<div className="border-b border-surface-variant mb-6 flex gap-8">
<button className="font-body-md text-body-md text-primary border-b-2 border-primary pb-3 font-medium">Order History &amp; Tracking</button>
<button className="font-body-md text-body-md text-on-surface-variant hover:text-on-background pb-3 transition-colors">Profile Settings</button>
</div>
<div className="flex flex-col gap-card-gap">
{/*  Order History Section (Card)  */}
<section className="bg-surface-container-lowest border border-surface-variant rounded flex flex-col">
<div className="px-container-padding py-4 border-b border-surface-variant flex justify-between items-center bg-surface-bright rounded-t">
<h2 className="font-h2 text-h2 text-on-background">Recent Orders</h2>
<button className="font-body-sm text-body-sm text-primary hover:text-on-primary-fixed-variant transition-colors flex items-center gap-1">
                                View All <span className="material-symbols-outlined text-[16px]">arrow_forward</span>
</button>
</div>
<div className="w-full overflow-x-auto">
<table className="w-full text-left border-collapse">
<thead>
<tr className="border-b border-surface-variant bg-surface-container-low">
<th className="font-label-caps text-label-caps text-on-surface-variant px-table-cell-padding uppercase tracking-wider">Order ID</th>
<th className="font-label-caps text-label-caps text-on-surface-variant px-table-cell-padding uppercase tracking-wider">Date</th>
<th className="font-label-caps text-label-caps text-on-surface-variant px-table-cell-padding uppercase tracking-wider">Items</th>
<th className="font-label-caps text-label-caps text-on-surface-variant px-table-cell-padding uppercase tracking-wider">Total</th>
<th className="font-label-caps text-label-caps text-on-surface-variant px-table-cell-padding uppercase tracking-wider">Status</th>
<th className="px-table-cell-padding"></th>
</tr>
</thead>
<tbody className="font-data-tabular text-data-tabular text-on-background">
<tr className="border-b border-surface-variant hover:bg-surface-container-low transition-colors">
<td className="px-table-cell-padding font-medium">#ORD-2023-8942</td>
<td className="px-table-cell-padding text-on-surface-variant">Oct 24, 2023</td>
<td className="px-table-cell-padding">3 items</td>
<td className="px-table-cell-padding">$245.00</td>
<td className="px-table-cell-padding">
<span className="inline-block px-2 py-1 bg-[#E0F2FE] text-[#0369A1] font-label-caps text-label-caps uppercase rounded-sm border border-[#BAE6FD]">In Transit</span>
</td>
<td className="px-table-cell-padding text-right">
<button className="text-primary hover:text-on-primary-fixed-variant font-body-sm text-body-sm">Track</button>
</td>
</tr>
<tr className="border-b border-surface-variant hover:bg-surface-container-low transition-colors">
<td className="px-table-cell-padding font-medium">#ORD-2023-8810</td>
<td className="px-table-cell-padding text-on-surface-variant">Oct 12, 2023</td>
<td className="px-table-cell-padding">1 item</td>
<td className="px-table-cell-padding">$89.99</td>
<td className="px-table-cell-padding">
<span className="inline-block px-2 py-1 bg-[#DCFCE7] text-[#15803D] font-label-caps text-label-caps uppercase rounded-sm border border-[#BBF7D0]">Delivered</span>
</td>
<td className="px-table-cell-padding text-right">
<button className="text-primary hover:text-on-primary-fixed-variant font-body-sm text-body-sm">Details</button>
</td>
</tr>
<tr className="hover:bg-surface-container-low transition-colors">
<td className="px-table-cell-padding font-medium">#ORD-2023-8755</td>
<td className="px-table-cell-padding text-on-surface-variant">Sep 28, 2023</td>
<td className="px-table-cell-padding">5 items</td>
<td className="px-table-cell-padding">$412.50</td>
<td className="px-table-cell-padding">
<span className="inline-block px-2 py-1 bg-[#F3F4F6] text-[#4B5563] font-label-caps text-label-caps uppercase rounded-sm border border-[#E5E7EB]">Completed</span>
</td>
<td className="px-table-cell-padding text-right">
<button className="text-primary hover:text-on-primary-fixed-variant font-body-sm text-body-sm">Details</button>
</td>
</tr>
</tbody>
</table>
</div>
</section>
{/*  Profile Settings Preview (Bento-style layout to demonstrate non-standard list)  */}
<div className="grid grid-cols-1 md:grid-cols-3 gap-card-gap mt-4">
<div className="md:col-span-2 bg-surface-container-lowest border border-surface-variant rounded p-container-padding flex flex-col gap-6">
<h3 className="font-h2 text-h2 text-on-background border-b border-surface-variant pb-2">Quick Settings</h3>
<form className="grid grid-cols-1 md:grid-cols-2 gap-6">
<div className="flex flex-col gap-2">
<label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Full Name</label>
<input className="w-full px-3 py-2 bg-surface-container-lowest border border-outline-variant rounded focus:border-primary focus:ring-2 focus:ring-primary-fixed-dim outline-none font-body-md text-body-md text-on-background transition-all" type="text" value="Alex Rivers" />
</div>
<div className="flex flex-col gap-2">
<label className="font-label-caps text-label-caps text-on-surface-variant uppercase">Email Address</label>
<input className="w-full px-3 py-2 bg-surface-container-low border border-outline-variant rounded focus:border-primary outline-none font-body-md text-body-md text-on-surface-variant" readOnly type="email" value="alex.rivers@enterprise.com" />
</div>
<div className="md:col-span-2 flex justify-end mt-2">
<button className="bg-primary text-on-primary font-body-sm text-body-sm px-4 py-2 rounded hover:bg-on-primary-fixed-variant transition-colors" type="button">Save Changes</button>
</div>
</form>
</div>
<div className="bg-surface-container-lowest border border-surface-variant rounded p-container-padding flex flex-col gap-4">
<h3 className="font-h2 text-h2 text-on-background border-b border-surface-variant pb-2">Security</h3>
<div className="flex flex-col gap-4">
<div className="flex items-center justify-between">
<span className="font-body-sm text-body-sm text-on-background">Two-Factor Auth</span>
<span className="inline-block px-2 py-1 bg-[#DCFCE7] text-[#15803D] font-label-caps text-label-caps uppercase rounded-sm border border-[#BBF7D0]">Enabled</span>
</div>
<div className="flex items-center justify-between">
<span className="font-body-sm text-body-sm text-on-background">Password</span>
<button className="text-primary hover:underline font-body-sm text-body-sm">Update</button>
</div>
</div>
</div>
</div>
</div>
</div>
</main>
</div>
    </div>
  );
}
