/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/product_detail_page/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
import { notFound } from "next/navigation";
import { getProductBySlug } from "@/lib/products";
import { AddToCartForm } from "@/app/(storefront)/products/add-to-cart-form";

const fmt = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  minimumFractionDigits: 2,
});

type Props = { params: Promise<{ slug: string }> };

export default async function Page({ params }: Props) {
  const { slug } = await params;
  const product = await getProductBySlug(slug);
  if (!product) notFound();
  const mainImage = product.images[0]?.url ?? "https://lh3.googleusercontent.com/aida-public/AB6AXuAZa-wnC3l4ftVBCIHFxNhRXoedM9miJQk3gLJeYXYlBj3dZlPskTvyPMKdz6bgfp__xpqi-IjD5KZ8STLOMHo5IrDxQmCf34upnOU69mlYsS4PsiC0Qnr-F5VI-u55KyhYw3mSYFlRDyO0-DIlt1D7mM8U8ZhSF6vcYZPFlGVIeKnGorIkvm8VjjuJE0O-dC514vQXqRiihT9boOIf3eNJmAx3jLvbKsCCYyWByq8_l5l_ro8iO4lDJsclHp4ElXNQTBPNcjO77AnB";
  return (
    <div className={`bg-background min-h-screen text-on-background antialiased font-body-md text-body-md`}>
<nav className="fixed top-0 w-full z-50 flex justify-between items-center px-6 h-16 max-w-[1440px] mx-auto bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
<div className="flex items-center gap-8">
<div className="text-xl font-black text-gray-900 dark:text-white">EnterpriseStore</div>
<div className="hidden md:flex items-center gap-1">
<a className="px-3 py-2 text-blue-600 dark:text-blue-400 border-b-2 border-blue-600 pb-1 font-inter text-sm font-medium" href="#">Shop</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Categories</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Deals</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Support</a>
</div>
</div>
<div className="flex items-center gap-4">
<div className="relative hidden sm:block">
<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-[20px]">search</span>
<input className="pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-800 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none w-64 transition-all" placeholder="Search inventory..." type="text" />
</div>
<button className="p-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors rounded-full flex items-center justify-center">
<span className="material-symbols-outlined">shopping_cart</span>
</button>
<button className="p-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors rounded-full flex items-center justify-center">
<span className="material-symbols-outlined">account_circle</span>
</button>
</div>
</nav>
<main className="pt-24 pb-16 px-6 max-w-[1440px] mx-auto">
<div className="flex items-center gap-2 text-on-surface-variant font-body-sm text-body-sm mb-6">
<a className="hover:text-primary transition-colors" href="#">Hardware</a>
<span className="material-symbols-outlined text-[16px]">chevron_right</span>
<a className="hover:text-primary transition-colors" href="#">{product.category?.name ?? "All Products"}</a>
<span className="material-symbols-outlined text-[16px]">chevron_right</span>
<span className="text-on-surface font-medium">{product.name}</span>
</div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-card-gap items-start">
<div className="lg:col-span-7 bg-surface-container-lowest border border-surface-variant rounded-xl p-container-padding flex flex-col gap-card-gap">
<div className="aspect-[4/3] rounded-lg bg-surface-container overflow-hidden border border-outline-variant relative">
<img alt={product.name} className="w-full h-full object-cover" src={mainImage} />
</div>
{product.images.length > 1 ? (
<div className="grid grid-cols-4 gap-inline-element-gap">
{product.images.map((img, i) => (
<button
  key={img.id}
  className={`aspect-square rounded-lg overflow-hidden cursor-pointer ${i === 0 ? "border-2 border-primary" : "border border-outline-variant hover:border-outline transition-colors opacity-70 hover:opacity-100"}`}
>
<img alt={img.alt ?? `${product.name} ${i + 1}`} className="w-full h-full object-cover" src={img.url} />
</button>
))}
</div>
) : null}
</div>
<div className="lg:col-span-5 bg-surface-container-lowest border border-surface-variant rounded-xl p-container-padding flex flex-col gap-6 sticky top-24">
<div className="flex flex-col gap-2">
<div className="flex justify-between items-start gap-4">
<h1 className="font-h1 text-h1 text-on-surface">{product.name}</h1>
<button className="p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container rounded-full transition-colors">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>bookmark</span>
</button>
</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">SKU: {product.id.slice(0, 12).toUpperCase()}</div>
</div>
<div className="flex items-center gap-3">
<span className="font-h1 text-[32px] font-bold tracking-tight text-on-surface">{fmt.format(product.price)}</span>
{product.compareAt ? <span className="font-body-md text-body-md text-on-surface-variant line-through">{fmt.format(product.compareAt)}</span> : null}
</div>
{product.stock > 0 ? (
<div className="flex items-center gap-2 bg-secondary-container text-on-secondary-container px-3 py-1.5 rounded w-fit border border-secondary-fixed-dim">
<span className="material-symbols-outlined text-[18px]">check_circle</span>
<span className="font-label-caps text-label-caps uppercase tracking-wider">In Stock - {product.stock} units left</span>
</div>
) : (
<div className="flex items-center gap-2 bg-error-container text-on-error-container px-3 py-1.5 rounded w-fit border border-error-container">
<span className="material-symbols-outlined text-[18px]">cancel</span>
<span className="font-label-caps text-label-caps uppercase tracking-wider">Out of Stock</span>
</div>
)}
<div className="h-[1px] bg-outline-variant w-full my-2"></div>
<div className="flex flex-col gap-3">
<h2 className="font-h2 text-h2 text-on-surface">Description</h2>
<p className="font-body-md text-body-md text-on-surface-variant leading-relaxed whitespace-pre-line">
{product.description ?? "Belum ada deskripsi untuk produk ini."}
</p>
</div>
<AddToCartForm productId={product.id} stock={product.stock} />
<div className="flex items-center justify-center gap-6 mt-4 text-on-surface-variant font-body-sm text-body-sm">
<div className="flex items-center gap-1">
<span className="material-symbols-outlined text-[16px]">local_shipping</span>
                        Next day delivery
                    </div>
<div className="flex items-center gap-1">
<span className="material-symbols-outlined text-[16px]">verified</span>
                        3-Year Warranty
                    </div>
</div>
</div>
</div>
</main>
    </div>
  );
}
