/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/product_detail_page/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
export default function Page() {
  return (
    <div className={`bg-background min-h-screen text-on-background antialiased font-body-md text-body-md`}>
<nav className="fixed top-0 w-full z-50 flex justify-between items-center px-6 h-16 max-w-[1440px] mx-auto bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
<div className="flex items-center gap-8">
<div className="text-xl font-black text-gray-900 dark:text-white">EnterpriseStore</div>
<div className="hidden md:flex items-center gap-1">
<a className="px-3 py-2 text-blue-600 dark:text-blue-400 border-b-2 border-blue-600 pb-1 font-inter text-sm font-medium" href="#">Shop</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Categories</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Deals</a>
<a className="px-3 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white font-inter text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors" href="#">Support</a>
</div>
</div>
<div className="flex items-center gap-4">
<div className="relative hidden sm:block">
<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-[20px]">search</span>
<input className="pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-800 text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none w-64 transition-all" placeholder="Search inventory..." type="text" />
</div>
<button className="p-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors rounded-full flex items-center justify-center">
<span className="material-symbols-outlined">shopping_cart</span>
</button>
<button className="p-2 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors rounded-full flex items-center justify-center">
<span className="material-symbols-outlined">account_circle</span>
</button>
</div>
</nav>
<main className="pt-24 pb-16 px-6 max-w-[1440px] mx-auto">
<div className="flex items-center gap-2 text-on-surface-variant font-body-sm text-body-sm mb-6">
<a className="hover:text-primary transition-colors" href="#">Hardware</a>
<span className="material-symbols-outlined text-[16px]">chevron_right</span>
<a className="hover:text-primary transition-colors" href="#">Server Infrastructure</a>
<span className="material-symbols-outlined text-[16px]">chevron_right</span>
<span className="text-on-surface font-medium">Edge Compute Node CX-900</span>
</div>
<div className="grid grid-cols-1 lg:grid-cols-12 gap-card-gap items-start">
<div className="lg:col-span-7 bg-surface-container-lowest border border-surface-variant rounded-xl p-container-padding flex flex-col gap-card-gap">
<div className="aspect-[4/3] rounded-lg bg-surface-container overflow-hidden border border-outline-variant relative">
<img alt="Main Product Image" className="w-full h-full object-cover" data-alt="High-end professional studio shot of a sleek, dark gray enterprise server rack unit with glowing blue LED status indicators, sharp focus, clean corporate aesthetic, resting on a clean white surface" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAZa-wnC3l4ftVBCIHFxNhRXoedM9miJQk3gLJeYXYlBj3dZlPskTvyPMKdz6bgfp__xpqi-IjD5KZ8STLOMHo5IrDxQmCf34upnOU69mlYsS4PsiC0Qnr-F5VI-u55KyhYw3mSYFlRDyO0-DIlt1D7mM8U8ZhSF6vcYZPFlGVIeKnGorIkvm8VjjuJE0O-dC514vQXqRiihT9boOIf3eNJmAx3jLvbKsCCYyWByq8_l5l_ro8iO4lDJsclHp4ElXNQTBPNcjO77AnB" />
</div>
<div className="grid grid-cols-4 gap-inline-element-gap">
<button className="aspect-square rounded-lg border-2 border-primary overflow-hidden cursor-pointer">
<img alt="Thumbnail 1" className="w-full h-full object-cover" data-alt="Front view detail of enterprise server unit showing cooling vents and drive bays, clean studio lighting" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCsJ4x2-1QJkdlpiAdtZF1mDCkk2S-Z23zZYrwFfKMV2AfKOROyZT7Di18VhZHc7MF4b3UINa4iin4Fx2VkPwyr5FL_BChQkCQTycjrUsp5PyNS7Ev-k_DDcWVq3TYGi0R4POhcx0Klb-s8e3tDrOW-JI0xBrViWhEw7UpiX4rcnRbD-4hajsS-ueRtl26L1kZfld7LhmooNuaNPHYNIx_z3zyvKVWLp58uYnt4xh4v45LR9T6AVSkmNl3OclLdkTOsCYYL32lyjmO_" />
</button>
<button className="aspect-square rounded-lg border border-outline-variant hover:border-outline transition-colors overflow-hidden cursor-pointer opacity-70 hover:opacity-100">
<img alt="Thumbnail 2" className="w-full h-full object-cover" data-alt="Rear view of network switch showing multiple ethernet ports and redundant power supply inputs, clinical lighting" src="https://lh3.googleusercontent.com/aida-public/AB6AXuD1jry_t7qL-KJcX8ahXTSi_FEy7iocJuOzjXYKAMumqgi-aXJVfjwr-6BoPH3DaloxvFDGQqF4IBsGRt7rxTmS-wAW7blj0gtHMjUdTD2jvFkyRw0DTSTEoPpxutf8UUzc_yWPm5IQeqL67AXrBYnH7AYc23qbHtoLP-Tc4q1G-m_UBI6VIxKsKHkrU15CW_rmM4vF8fWOlSHUWM_XaFHyT4ZwuAyzOrljpElhuB8lV3DXMDIFetWtnjTg5W0YrCn_gN83Zv7hzQSj" />
</button>
<button className="aspect-square rounded-lg border border-outline-variant hover:border-outline transition-colors overflow-hidden cursor-pointer opacity-70 hover:opacity-100">
<img alt="Thumbnail 3" className="w-full h-full object-cover" data-alt="Close up macro shot of internal server motherboard components and processing chips, cool technical blue tint" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCLVF3Ta1IDizUJDWiKkuAmqv-0wqFEQitRn8our5Q1FuUXL1-RcbiD3zx9dQsFRfBeiz-FyRLb3QOnYiCHK6PaF4EZudPae2G2ZgCo7KdXqzQASFtdNMojVvmyF8i5ora_Z37lBOomf_7KtVnvrntedx6SByoxNBu7YUFzHqKYalURi2gaaGUha-Cs0MPY9h46VD7pZvqbzG8s_Doe_PzHmwDdQvKxNk6Mo4odDRDnMMMmDaDjNyHMp2j2TPwz9rBudCghuZD81pUW" />
</button>
<button className="aspect-square rounded-lg border border-outline-variant hover:border-outline transition-colors overflow-hidden cursor-pointer opacity-70 hover:opacity-100 bg-surface-container flex items-center justify-center">
<span className="material-symbols-outlined text-outline text-[32px]">play_circle</span>
</button>
</div>
</div>
<div className="lg:col-span-5 bg-surface-container-lowest border border-surface-variant rounded-xl p-container-padding flex flex-col gap-6 sticky top-24">
<div className="flex flex-col gap-2">
<div className="flex justify-between items-start gap-4">
<h1 className="font-h1 text-h1 text-on-surface">Edge Compute Node CX-900</h1>
<button className="p-2 text-on-surface-variant hover:text-primary hover:bg-surface-container rounded-full transition-colors">
<span className="material-symbols-outlined" style={{ fontVariationSettings: "'FILL' 0" }}>bookmark</span>
</button>
</div>
<div className="font-body-sm text-body-sm text-on-surface-variant">SKU: ENT-CX900-V2</div>
</div>
<div className="flex items-center gap-3">
<span className="font-h1 text-[32px] font-bold tracking-tight text-on-surface">$3,499.00</span>
<span className="font-body-md text-body-md text-on-surface-variant line-through">$3,899.00</span>
</div>
<div className="flex items-center gap-2 bg-secondary-container text-on-secondary-container px-3 py-1.5 rounded w-fit border border-secondary-fixed-dim">
<span className="material-symbols-outlined text-[18px]">check_circle</span>
<span className="font-label-caps text-label-caps uppercase tracking-wider">In Stock - 5 units left</span>
</div>
<div className="h-[1px] bg-outline-variant w-full my-2"></div>
<div className="flex flex-col gap-3">
<h2 className="font-h2 text-h2 text-on-surface">Description</h2>
<p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
                        High-density 1U rackmount server engineered for latency-sensitive edge computing and local data caching. The CX-900 features dual redundant hot-swappable 800W power supplies, tool-less NVMe drive bays, and robust thermal management designed for unconditioned environments. Ideal for branch office deployments and distributed AI inference workloads.
                    </p>
<ul className="flex flex-col gap-2 mt-2 font-body-sm text-body-sm text-on-surface-variant">
<li className="flex items-start gap-2">
<span className="material-symbols-outlined text-[16px] text-primary mt-0.5">memory</span>
                            Dual 24-Core Processors
                        </li>
<li className="flex items-start gap-2">
<span className="material-symbols-outlined text-[16px] text-primary mt-0.5">dns</span>
                            256GB ECC DDR5 Memory
                        </li>
<li className="flex items-start gap-2">
<span className="material-symbols-outlined text-[16px] text-primary mt-0.5">router</span>
                            4x 10GbE SFP+ Networking
                        </li>
</ul>
</div>
<div className="flex flex-col gap-4 mt-4">
<div className="flex items-center gap-4">
<label className="font-data-tabular text-data-tabular text-on-surface w-16">Qty</label>
<div className="flex items-center border border-outline-variant rounded-lg overflow-hidden h-10 w-32">
<button className="w-10 h-full flex items-center justify-center bg-surface-container-low hover:bg-surface-container text-on-surface transition-colors">
<span className="material-symbols-outlined text-[18px]">remove</span>
</button>
<input className="w-full h-full text-center border-none bg-surface-container-lowest font-data-tabular text-data-tabular text-on-surface focus:ring-0 p-0" type="text" value="1" />
<button className="w-10 h-full flex items-center justify-center bg-surface-container-low hover:bg-surface-container text-on-surface transition-colors">
<span className="material-symbols-outlined text-[18px]">add</span>
</button>
</div>
</div>
<div className="flex flex-col gap-3 mt-2">
<button className="w-full bg-primary text-on-primary font-body-md text-body-md font-medium h-12 rounded-lg flex items-center justify-center gap-2 hover:bg-primary-container hover:text-on-primary-container transition-colors shadow-sm">
<span className="material-symbols-outlined text-[20px]">shopping_cart</span>
                            Add to cart
                        </button>
<button className="w-full border border-outline text-on-surface font-body-md text-body-md font-medium h-12 rounded-lg flex items-center justify-center gap-2 hover:bg-surface-container-low transition-colors">
<span className="material-symbols-outlined text-[20px]">bolt</span>
                            Buy now
                        </button>
</div>
</div>
<div className="flex items-center justify-center gap-6 mt-4 text-on-surface-variant font-body-sm text-body-sm">
<div className="flex items-center gap-1">
<span className="material-symbols-outlined text-[16px]">local_shipping</span>
                        Next day delivery
                    </div>
<div className="flex items-center gap-1">
<span className="material-symbols-outlined text-[16px]">verified</span>
                        3-Year Warranty
                    </div>
</div>
</div>
</div>
</main>
    </div>
  );
}
