/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/product_catalog/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
export default function Page() {
  return (
    <div className={`bg-surface text-on-surface font-body-md text-body-md antialiased min-h-screen flex flex-col`}>
{/*  TopNavBar Shared Component  */}
<header className="fixed top-0 w-full z-50 bg-surface-container-lowest border-b border-surface-variant flex justify-between items-center px-6 h-16 mx-auto">
<div className="flex items-center gap-8">
<div className="font-h1 text-h1 font-black text-on-background tracking-tight">EnterpriseStore</div>
<nav className="hidden md:flex items-center gap-6 mt-1">
<a className="font-body-md text-body-md font-medium text-primary border-b-2 border-primary pb-1" href="#">Shop</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Categories</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Deals</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Support</a>
</nav>
</div>
<div className="flex items-center gap-4">
<div className="relative hidden lg:flex items-center">
<span className="material-symbols-outlined absolute left-3 text-on-surface-variant text-[20px]">search</span>
<input className="pl-10 pr-4 py-1.5 w-64 bg-surface border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all placeholder:text-on-surface-variant" placeholder="Search catalog..." type="text" />
</div>
<button className="text-on-surface-variant hover:text-on-surface p-2 rounded-DEFAULT hover:bg-surface-container transition-colors flex items-center justify-center active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="shopping_cart">shopping_cart</span>
</button>
<button className="text-on-surface-variant hover:text-on-surface p-2 rounded-DEFAULT hover:bg-surface-container transition-colors flex items-center justify-center active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="account_circle">account_circle</span>
</button>
</div>
</header>
{/*  Main Content Canvas  */}
<main className="flex-1 pt-24 pb-12 px-6 w-full max-w-[1440px] mx-auto flex flex-col md:flex-row gap-6 items-start">
{/*  Filter Sidebar  */}
<aside className="w-full md:w-64 flex-shrink-0 bg-surface-container-lowest border border-surface-variant rounded-DEFAULT p-5 flex flex-col gap-6 sticky top-24">
{/*  Applied Filters  */}
<div>
<h3 className="font-label-caps text-label-caps text-on-surface-variant uppercase mb-3">Active Filters</h3>
<div className="flex flex-wrap gap-2">
<span className="inline-flex items-center gap-1 px-2 py-1 bg-surface-container border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm text-on-surface">
                        Laptops
                        <span className="material-symbols-outlined text-[14px] cursor-pointer hover:text-error">close</span>
</span>
<span className="inline-flex items-center gap-1 px-2 py-1 bg-surface-container border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm text-on-surface">
                        In Stock
                        <span className="material-symbols-outlined text-[14px] cursor-pointer hover:text-error">close</span>
</span>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Categories  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Categories</h3>
<div className="flex flex-col gap-2">
<label className="flex items-center gap-3 cursor-pointer group">
<input checked className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Laptops &amp; Workstations</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Monitors &amp; Displays</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Networking Gear</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Server Components</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Peripherals</span>
</label>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Price Range  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Price Range</h3>
<div className="flex items-center gap-2">
<div className="relative flex-1">
<span className="absolute left-2 top-1/2 -translate-y-1/2 text-on-surface-variant font-body-sm text-body-sm">$</span>
<input className="w-full pl-6 pr-2 py-1.5 bg-surface-container-lowest border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none text-on-surface" placeholder="Min" type="number" />
</div>
<span className="text-on-surface-variant">-</span>
<div className="relative flex-1">
<span className="absolute left-2 top-1/2 -translate-y-1/2 text-on-surface-variant font-body-sm text-body-sm">$</span>
<input className="w-full pl-6 pr-2 py-1.5 bg-surface-container-lowest border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none text-on-surface" placeholder="Max" type="number" />
</div>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Rating  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Minimum Rating</h3>
<div className="flex flex-col gap-2">
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 border-outline-variant text-primary focus:ring-primary bg-surface-container-lowest" name="rating" type="radio" />
<div className="flex items-center text-tertiary-container">
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="ml-2 font-body-sm text-body-sm text-on-surface">&amp; Up</span>
</div>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 border-outline-variant text-primary focus:ring-primary bg-surface-container-lowest" name="rating" type="radio" />
<div className="flex items-center text-tertiary-container">
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="ml-2 font-body-sm text-body-sm text-on-surface">&amp; Up</span>
</div>
</label>
</div>
</div>
<button className="w-full mt-2 bg-surface text-on-surface border border-outline font-body-md text-body-md font-medium py-2 rounded-DEFAULT hover:bg-surface-container transition-colors">Clear All</button>
</aside>
{/*  Product Grid Area  */}
<div className="flex-1 flex flex-col gap-4">
{/*  Utility Bar  */}
<div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-surface-container-lowest border border-surface-variant rounded-DEFAULT p-3">
<div className="font-body-md text-body-md text-on-surface">Showing <span className="font-semibold">1-12</span> of 48 results</div>
<div className="flex items-center gap-3">
<span className="font-body-sm text-body-sm text-on-surface-variant">Sort by:</span>
<select className="bg-surface-container-lowest border border-outline-variant rounded-DEFAULT px-3 py-1.5 font-body-sm text-body-sm text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none">
<option>Relevance</option>
<option>Price: Low to High</option>
<option>Price: High to Low</option>
<option>Highest Rated</option>
</select>
<div className="flex border border-outline-variant rounded-DEFAULT overflow-hidden ml-2">
<button className="p-1.5 bg-surface-container text-on-surface hover:bg-surface-variant transition-colors"><span className="material-symbols-outlined text-[20px]">grid_view</span></button>
<button className="p-1.5 bg-surface-container-lowest text-on-surface-variant hover:bg-surface transition-colors border-l border-outline-variant"><span className="material-symbols-outlined text-[20px]">view_list</span></button>
</div>
</div>
</div>
{/*  Grid  */}
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
{/*  Product Card 1  */}
<div className="bg-surface-container-lowest border border-surface-variant rounded-DEFAULT overflow-hidden flex flex-col group hover:border-outline transition-colors">
<div className="h-48 w-full bg-surface-container relative p-4 flex items-center justify-center">
<div className="absolute top-2 left-2 bg-surface-container-lowest text-primary border border-outline-variant px-1.5 py-0.5 rounded-DEFAULT font-label-caps text-label-caps uppercase">New</div>
<img alt="Product Image" className="max-h-full max-w-full object-contain mix-blend-multiply" data-alt="sleek professional laptop open on clean white studio background with soft lighting" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDJiKMniu0k7DHTnYurAWnrxEHhHQ6x3hjrQtrXnkDy_nqLTMVMNWkTmf7QT2b1TiGV4pb9xNK8cH8U6k6ixlb2_yw0BvKFAt0oIVgo3tyjbzkuS6YleqNfCZgAaZ0uiXGSOyOTYVSJjygeRndrBxVPEBG0FLuofbQDeu8Jy0ZNsqpOXedLns0k47WxspdcO1nl3as0LQLMWTvLgyMb9oK0s27lp3k8h49KiJ1D3WOQh9nX3_q13g9by1B-_8aqcfGOnwwvzbyRK4_F" />
</div>
<div className="p-4 flex flex-col flex-1 border-t border-surface-variant">
<div className="font-body-sm text-body-sm text-on-surface-variant mb-1">Dell Technologies</div>
<h4 className="font-body-md text-body-md font-medium text-on-background mb-1 leading-snug line-clamp-2">Latitude 7420 Enterprise Notebook</h4>
<div className="flex items-center gap-1 mb-3">
<span className="material-symbols-outlined text-[14px] text-tertiary-container" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="font-data-tabular text-data-tabular text-on-surface">4.8</span>
<span className="font-body-sm text-body-sm text-on-surface-variant ml-1">(124)</span>
</div>
<div className="mt-auto flex items-end justify-between">
<div>
<div className="font-body-sm text-body-sm text-on-surface-variant line-through">$1,499.00</div>
<div className="font-h2 text-h2 text-on-background">$1,249.00</div>
</div>
<button className="border border-outline text-primary hover:bg-surface-container px-3 py-1.5 rounded-DEFAULT font-body-sm text-body-sm font-medium transition-colors flex items-center gap-1">
<span className="material-symbols-outlined text-[18px]">add_shopping_cart</span>
                                Add
                            </button>
</div>
</div>
</div>
{/*  Product Card 2  */}
<div className="bg-surface-container-lowest border border-surface-variant rounded-DEFAULT overflow-hidden flex flex-col group hover:border-outline transition-colors">
<div className="h-48 w-full bg-surface-container relative p-4 flex items-center justify-center">
<img alt="Product Image" className="max-h-full max-w-full object-contain mix-blend-multiply" data-alt="high resolution curved dual monitor setup on clinical white background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDjnm94DbTcuxcGqCWHjwDlG0EoLnKwdm85pI8_-LoPn7-EjskWbTkagCPS3XoC6SHywyB1PinuYqShZOcvEXOBT7CtZS1GaE4zJal8ui4hyHZX4eDImxsT2oy6vC0Lh-42xz0FEm9nNVPxOsiIYgh0NxVGC3dWWnQ_ZuYW-y0Agf8E44H-etCgC5hylqDKjKtjHEMBFjsXWLQTRKebmYDm19Iiuw47riIEUND8FN7ZbwEPPogX3iHyFygBVUMwZ-jN0LHgRaOu1Pac" />
</div>
<div className="p-4 flex flex-col flex-1 border-t border-surface-variant">
<div className="font-body-sm text-body-sm text-on-surface-variant mb-1">Samsung</div>
<h4 className="font-body-md text-body-md font-medium text-on-background mb-1 leading-snug line-clamp-2">Odyssey G9 49" Curved Business Monitor</h4>
<div className="flex items-center gap-1 mb-3">
<span className="material-symbols-outlined text-[14px] text-tertiary-container" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="font-data-tabular text-data-tabular text-on-surface">4.9</span>
<span className="font-body-sm text-body-sm text-on-surface-variant ml-1">(89)</span>
</div>
<div className="mt-auto flex items-end justify-between">
<div>
<div className="font-h2 text-h2 text-on-background">$1,199.99</div>
</div>
<button className="border border-outline text-primary hover:bg-surface-container px-3 py-1.5 rounded-DEFAULT font-body-sm text-body-sm font-medium transition-colors flex items-center gap-1">
<span className="material-symbols-outlined text-[18px]">add_shopping_cart</span>
                                Add
                            </button>
</div>
</div>
</div>
{/*  Product Card 3  */}
<div className="bg-surface-container-lowest border border-surface-variant rounded-DEFAULT overflow-hidden flex flex-col group hover:border-outline transition-colors">
<div className="h-48 w-full bg-surface-container relative p-4 flex items-center justify-center">
<div className="absolute top-2 left-2 bg-error-container text-on-error-container border border-error-container px-1.5 py-0.5 rounded-DEFAULT font-label-caps text-label-caps uppercase">Low Stock</div>
<img alt="Product Image" className="max-h-full max-w-full object-contain mix-blend-multiply" data-alt="enterprise grade network switch router stacked against pure white background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBDLXKFnZ7nty988zIkJpFdvsPbgsoUYZmwW4OUR1oCUGwpD5rQdj3Kc9fqnsI5UPPUwb6z0fEB4WY21L605hQEMPgA4Lbx6Dre8B37aZrZPAe1Ijpg0eojmlWHsk6yenIFqGSegxg3rhHc7Dq4GYgzKcrNwIuWhIezoLtOfdPltaTvBT5fHmaG5pRoehYbBEesLv8PnFXrypMR7gbweq5ajjipH5YoFSEW0qVj4zfbKtF6pKCH3DMLK8s-rVVPoNqG9sMksQwlHZIB" />
</div>
<div className="p-4 flex flex-col flex-1 border-t border-surface-variant">
<div className="font-body-sm text-body-sm text-on-surface-variant mb-1">Cisco Systems</div>
<h4 className="font-body-md text-body-md font-medium text-on-background mb-1 leading-snug line-clamp-2">Catalyst 9300 48-port Network Switch</h4>
<div className="flex items-center gap-1 mb-3">
<span className="material-symbols-outlined text-[14px] text-tertiary-container" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="font-data-tabular text-data-tabular text-on-surface">4.7</span>
<span className="font-body-sm text-body-sm text-on-surface-variant ml-1">(42)</span>
</div>
<div className="mt-auto flex items-end justify-between">
<div>
<div className="font-h2 text-h2 text-on-background">$3,450.00</div>
</div>
<button className="border border-outline text-primary hover:bg-surface-container px-3 py-1.5 rounded-DEFAULT font-body-sm text-body-sm font-medium transition-colors flex items-center gap-1">
<span className="material-symbols-outlined text-[18px]">add_shopping_cart</span>
                                Add
                            </button>
</div>
</div>
</div>
{/*  Product Card 4  */}
<div className="bg-surface-container-lowest border border-surface-variant rounded-DEFAULT overflow-hidden flex flex-col group hover:border-outline transition-colors">
<div className="h-48 w-full bg-surface-container relative p-4 flex items-center justify-center">
<img alt="Product Image" className="max-h-full max-w-full object-contain mix-blend-multiply" data-alt="minimalist wireless ergonomic mouse resting on flat neutral surface" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCZ7ukrY5u1g-eCr8YAgcnjx69er-_Uczt1-9xYWBiosXhwJm2t-ye28h9d3SuOrTELvZ0EIxzdCHLCA6tXBwB0fmrwWrJn_pOJa1S3a7IPPrU8eU-SCmwMdXO-ToihEdYhTrafLuN-crmcW_ihr53bc79qkBfRricgEZEiEf6DkRIpgHl99L_rCrCa0AVxDdUZo1ivofuVo9dXr7SLnPFHkjyrq4AzKVHh1eH1DDufVlkG5el5Z4SrvTw2w5KrFC4-9N7-QX61K3fw" />
</div>
<div className="p-4 flex flex-col flex-1 border-t border-surface-variant">
<div className="font-body-sm text-body-sm text-on-surface-variant mb-1">Logitech</div>
<h4 className="font-body-md text-body-md font-medium text-on-background mb-1 leading-snug line-clamp-2">MX Master 3S Advanced Wireless Mouse</h4>
<div className="flex items-center gap-1 mb-3">
<span className="material-symbols-outlined text-[14px] text-tertiary-container" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="font-data-tabular text-data-tabular text-on-surface">4.9</span>
<span className="font-body-sm text-body-sm text-on-surface-variant ml-1">(512)</span>
</div>
<div className="mt-auto flex items-end justify-between">
<div>
<div className="font-h2 text-h2 text-on-background">$99.99</div>
</div>
<button className="border border-outline text-primary hover:bg-surface-container px-3 py-1.5 rounded-DEFAULT font-body-sm text-body-sm font-medium transition-colors flex items-center gap-1">
<span className="material-symbols-outlined text-[18px]">add_shopping_cart</span>
                                Add
                            </button>
</div>
</div>
</div>
{/*  Product Card 5  */}
<div className="bg-surface-container-lowest border border-surface-variant rounded-DEFAULT overflow-hidden flex flex-col group hover:border-outline transition-colors">
<div className="h-48 w-full bg-surface-container relative p-4 flex items-center justify-center">
<img alt="Product Image" className="max-h-full max-w-full object-contain mix-blend-multiply" data-alt="premium over ear noise cancelling headphones on stark white studio background" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAuiz9Er5_Tac1_4Vo5_EWCLVztubsax3qodazovErRPdtz_VSac-B0E1AW4aMILMXa-SDyJHghvhmZym3_u4B4tp_Ne7nEMUZgZpSML7MlST5C9W90gR9leSOjHdb0YoXdXRXm90KhwjqAb1Nd6uTOb8bXWw_jBWTIJ5oj7l5wfohKmPKH1QugwUjm-ksh_j1D0imWG1S5QlL0S2TSvJhb15tIcSKAARYxdT_iEnjY5Uan-d0G9Iy0_wXvkLTx-7jluYFeJGucMduw" />
</div>
<div className="p-4 flex flex-col flex-1 border-t border-surface-variant">
<div className="font-body-sm text-body-sm text-on-surface-variant mb-1">Sony</div>
<h4 className="font-body-md text-body-md font-medium text-on-background mb-1 leading-snug line-clamp-2">WH-1000XM5 Noise Canceling Headphones</h4>
<div className="flex items-center gap-1 mb-3">
<span className="material-symbols-outlined text-[14px] text-tertiary-container" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="font-data-tabular text-data-tabular text-on-surface">4.8</span>
<span className="font-body-sm text-body-sm text-on-surface-variant ml-1">(340)</span>
</div>
<div className="mt-auto flex items-end justify-between">
<div>
<div className="font-h2 text-h2 text-on-background">$348.00</div>
</div>
<button className="border border-outline text-primary hover:bg-surface-container px-3 py-1.5 rounded-DEFAULT font-body-sm text-body-sm font-medium transition-colors flex items-center gap-1">
<span className="material-symbols-outlined text-[18px]">add_shopping_cart</span>
                                Add
                            </button>
</div>
</div>
</div>
</div>
{/*  Pagination  */}
<div className="mt-8 flex justify-center">
<div className="flex items-center border border-outline-variant rounded-DEFAULT bg-surface-container-lowest overflow-hidden">
<button className="px-3 py-2 text-on-surface-variant hover:bg-surface-container transition-colors border-r border-outline-variant flex items-center disabled:opacity-50"><span className="material-symbols-outlined text-[18px]">chevron_left</span></button>
<button className="px-4 py-2 font-data-tabular text-data-tabular bg-primary-container text-on-primary-container font-medium border-r border-outline-variant">1</button>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">2</button>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">3</button>
<span className="px-3 py-2 text-on-surface-variant border-r border-outline-variant">...</span>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">12</button>
<button className="px-3 py-2 text-on-surface hover:bg-surface-container transition-colors flex items-center"><span className="material-symbols-outlined text-[18px]">chevron_right</span></button>
</div>
</div>
</div>
</main>
    </div>
  );
}
