/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// AUTOGENERATED from template/product_catalog/code.html — preserves design exactly.
// To re-run conversion: python3 /tmp/portscript/html2tsx.py
import Link from "next/link";

import { listStorefrontProducts } from "@/lib/products";
import { ProductCard } from "./product-card";

export default async function Page() {
  const products = await listStorefrontProducts();
  return (
    <div className={`bg-surface text-on-surface font-body-md text-body-md antialiased min-h-screen flex flex-col`}>
{/*  TopNavBar Shared Component  */}
<header className="fixed top-0 w-full z-50 bg-surface-container-lowest border-b border-surface-variant flex justify-between items-center px-6 h-16 mx-auto">
<div className="flex items-center gap-8">
<div className="font-h1 text-h1 font-black text-on-background tracking-tight">EnterpriseStore</div>
<nav className="hidden md:flex items-center gap-6 mt-1">
<a className="font-body-md text-body-md font-medium text-primary border-b-2 border-primary pb-1" href="#">Shop</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Categories</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Deals</a>
<a className="font-body-md text-body-md font-medium text-on-surface-variant hover:text-on-surface hover:bg-surface-container transition-colors px-2 py-1 rounded-DEFAULT" href="#">Support</a>
</nav>
</div>
<div className="flex items-center gap-4">
<div className="relative hidden lg:flex items-center">
<span className="material-symbols-outlined absolute left-3 text-on-surface-variant text-[20px]">search</span>
<input className="pl-10 pr-4 py-1.5 w-64 bg-surface border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none transition-all placeholder:text-on-surface-variant" placeholder="Search catalog..." type="text" />
</div>
<button className="text-on-surface-variant hover:text-on-surface p-2 rounded-DEFAULT hover:bg-surface-container transition-colors flex items-center justify-center active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="shopping_cart">shopping_cart</span>
</button>
<button className="text-on-surface-variant hover:text-on-surface p-2 rounded-DEFAULT hover:bg-surface-container transition-colors flex items-center justify-center active:scale-95 transition-transform duration-150">
<span className="material-symbols-outlined" data-icon="account_circle">account_circle</span>
</button>
</div>
</header>
{/*  Main Content Canvas  */}
<main className="flex-1 pt-24 pb-12 px-6 w-full max-w-[1440px] mx-auto flex flex-col md:flex-row gap-6 items-start">
{/*  Filter Sidebar  */}
<aside className="w-full md:w-64 flex-shrink-0 bg-surface-container-lowest border border-surface-variant rounded-DEFAULT p-5 flex flex-col gap-6 sticky top-24">
{/*  Applied Filters  */}
<div>
<h3 className="font-label-caps text-label-caps text-on-surface-variant uppercase mb-3">Active Filters</h3>
<div className="flex flex-wrap gap-2">
<span className="inline-flex items-center gap-1 px-2 py-1 bg-surface-container border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm text-on-surface">
                        Laptops
                        <span className="material-symbols-outlined text-[14px] cursor-pointer hover:text-error">close</span>
</span>
<span className="inline-flex items-center gap-1 px-2 py-1 bg-surface-container border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm text-on-surface">
                        In Stock
                        <span className="material-symbols-outlined text-[14px] cursor-pointer hover:text-error">close</span>
</span>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Categories  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Categories</h3>
<div className="flex flex-col gap-2">
<label className="flex items-center gap-3 cursor-pointer group">
<input checked className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Laptops &amp; Workstations</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Monitors &amp; Displays</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Networking Gear</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Server Components</span>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 rounded-sm border-outline-variant text-primary focus:ring-primary focus:ring-offset-0 bg-surface-container-lowest" type="checkbox" />
<span className="font-body-sm text-body-sm text-on-surface group-hover:text-primary transition-colors">Peripherals</span>
</label>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Price Range  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Price Range</h3>
<div className="flex items-center gap-2">
<div className="relative flex-1">
<span className="absolute left-2 top-1/2 -translate-y-1/2 text-on-surface-variant font-body-sm text-body-sm">$</span>
<input className="w-full pl-6 pr-2 py-1.5 bg-surface-container-lowest border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none text-on-surface" placeholder="Min" type="number" />
</div>
<span className="text-on-surface-variant">-</span>
<div className="relative flex-1">
<span className="absolute left-2 top-1/2 -translate-y-1/2 text-on-surface-variant font-body-sm text-body-sm">$</span>
<input className="w-full pl-6 pr-2 py-1.5 bg-surface-container-lowest border border-outline-variant rounded-DEFAULT font-body-sm text-body-sm focus:border-primary focus:ring-1 focus:ring-primary outline-none text-on-surface" placeholder="Max" type="number" />
</div>
</div>
</div>
<hr className="border-surface-variant" />
{/*  Rating  */}
<div>
<h3 className="font-h2 text-h2 text-on-background mb-3">Minimum Rating</h3>
<div className="flex flex-col gap-2">
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 border-outline-variant text-primary focus:ring-primary bg-surface-container-lowest" name="rating" type="radio" />
<div className="flex items-center text-tertiary-container">
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="ml-2 font-body-sm text-body-sm text-on-surface">&amp; Up</span>
</div>
</label>
<label className="flex items-center gap-3 cursor-pointer group">
<input className="w-4 h-4 border-outline-variant text-primary focus:ring-primary bg-surface-container-lowest" name="rating" type="radio" />
<div className="flex items-center text-tertiary-container">
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]" style={{ fontVariationSettings: "'FILL' 1" }}>star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="material-symbols-outlined text-[18px]">star</span>
<span className="ml-2 font-body-sm text-body-sm text-on-surface">&amp; Up</span>
</div>
</label>
</div>
</div>
<button className="w-full mt-2 bg-surface text-on-surface border border-outline font-body-md text-body-md font-medium py-2 rounded-DEFAULT hover:bg-surface-container transition-colors">Clear All</button>
</aside>
{/*  Product Grid Area  */}
<div className="flex-1 flex flex-col gap-4">
{/*  Utility Bar  */}
<div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-surface-container-lowest border border-surface-variant rounded-DEFAULT p-3">
<div className="font-body-md text-body-md text-on-surface">Showing <span className="font-semibold">1-12</span> of 48 results</div>
<div className="flex items-center gap-3">
<span className="font-body-sm text-body-sm text-on-surface-variant">Sort by:</span>
<select className="bg-surface-container-lowest border border-outline-variant rounded-DEFAULT px-3 py-1.5 font-body-sm text-body-sm text-on-surface focus:border-primary focus:ring-1 focus:ring-primary outline-none">
<option>Relevance</option>
<option>Price: Low to High</option>
<option>Price: High to Low</option>
<option>Highest Rated</option>
</select>
<div className="flex border border-outline-variant rounded-DEFAULT overflow-hidden ml-2">
<button className="p-1.5 bg-surface-container text-on-surface hover:bg-surface-variant transition-colors"><span className="material-symbols-outlined text-[20px]">grid_view</span></button>
<button className="p-1.5 bg-surface-container-lowest text-on-surface-variant hover:bg-surface transition-colors border-l border-outline-variant"><span className="material-symbols-outlined text-[20px]">view_list</span></button>
</div>
</div>
</div>
{/*  Grid  */}
<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
{products.length === 0 ? (
<div className="col-span-full p-12 text-center text-on-surface-variant font-body-md text-body-md">
Belum ada produk tersedia. Admin bisa menambahkan dari <Link className="text-primary hover:underline" href="/admin/inventory/new">/admin/inventory/new</Link>.
</div>
) : (
products.map((product) => (<ProductCard key={product.id} product={product} />))
)}
</div>
{/*  Pagination  */}
<div className="mt-8 flex justify-center">
<div className="flex items-center border border-outline-variant rounded-DEFAULT bg-surface-container-lowest overflow-hidden">
<button className="px-3 py-2 text-on-surface-variant hover:bg-surface-container transition-colors border-r border-outline-variant flex items-center disabled:opacity-50"><span className="material-symbols-outlined text-[18px]">chevron_left</span></button>
<button className="px-4 py-2 font-data-tabular text-data-tabular bg-primary-container text-on-primary-container font-medium border-r border-outline-variant">1</button>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">2</button>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">3</button>
<span className="px-3 py-2 text-on-surface-variant border-r border-outline-variant">...</span>
<button className="px-4 py-2 font-data-tabular text-data-tabular text-on-surface hover:bg-surface-container transition-colors border-r border-outline-variant">12</button>
<button className="px-3 py-2 text-on-surface hover:bg-surface-container transition-colors flex items-center"><span className="material-symbols-outlined text-[18px]">chevron_right</span></button>
</div>
</div>
</div>
</main>
    </div>
  );
}
